### ISSUE TITLE
IndexNotFoundException: no such index

### ISSUE THREAD

**Issue by mrmodolo** [TheHive-Project/Cortex#103]
# IndexNotFoundException: no such index

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 16.04
| OS version (client)       | Ubuntu 16.04
| Cortex version / git hash   | cortex 2.0.4-1
| Package Type              | DEB
| Browser type & version    | Chrome

### Problem Description

```
[info] play.api.Play - Application started (Prod)
Mai 04 14:36:04 pfxapp0000353 cortex[2726]: [info] p.c.s.AkkaHttpServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9001
Mai 04 14:38:08 pfxapp0000353 cortex[2726]: [info] o.t.c.s.ErrorHandler - GET /api/user/current returned 520
Mai 04 14:38:08 pfxapp0000353 cortex[2726]: org.elasticsearch.transport.RemoteTransportException: [VXTecqz][127.0.0.1:9300][indices:data/read/search]
Mai 04 14:38:08 pfxapp0000353 cortex[2726]: Caused by: org.elasticsearch.index.IndexNotFoundException: no such index
Mai 04 14:38:08 pfxapp0000353 cortex[2726]:         at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver$WildcardExpressionResolver.indexNotFoundException(IndexNameEx
Mai 04 14:38:08 pfxapp0000353 cortex[2726]:         at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver$WildcardExpressionResolver.innerResolve(IndexNameExpressionRe
Mai 04 14:38:08 pfxapp0000353 cortex[2726]:         at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver$WildcardExpressionResolver.resolve(IndexNameExpressionResolve
Mai 04 14:38:08 pfxapp0000353 cortex[2726]:         at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndices(IndexNameExpressionResolver.java:164)
Mai 04 14:38:08 pfxapp0000353 cortex[2726]:         at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndices(IndexNameExpressionResolver.java:139)
Mai 04 14:38:08 pfxapp0000353 cortex[2726]:         at org.elasticsearch.action.search.TransportSearchAction.executeSearch(TransportSearchAction.java:294)
Mai 04 14:38:08 pfxapp0000353 cortex[2726]:         at org.elasticsearch.action.search.TransportSearchAction.lambda$doExecute$4(TransportSearchAction.java:193)
Mai 04 14:38:08 pfxapp0000353 cortex[2726]:         at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:60)
Mai 04 14:38:08 pfxapp0000353 cortex[2726]:         at org.elasticsearch.index.query.Rewriteable.rewriteAndFetch(Rewriteable.java:113)
Mai 04 14:38:08 pfxapp0000353 cortex[2726]:         at org.elasticsearch.index.query.Rewriteable.rewriteAndFetch(Rewriteable.java:86)
Mai 04 14:38:10 pfxapp0000353 cortex[2726]: [info] o.e.s.MigrationSrv - Create a new empty database
Mai 04 14:38:10 pfxapp0000353 cortex[2726]: [error] o.e.s.MigrationSrv - Migration fail
Mai 04 14:38:10 pfxapp0000353 cortex[2726]: org.elasticsearch.transport.RemoteTransportException: [VXTecqz][127.0.0.1:9300][indices:admin/create]
Mai 04 14:38:10 pfxapp0000353 cortex[2726]: Caused by: java.lang.IllegalArgumentException: Rejecting mapping update to [cortex_1] as the final mapping would have more than 1 type:
Mai 04 14:38:10 pfxapp0000353 cortex[2726]:         at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:501)
Mai 04 14:38:10 pfxapp0000353 cortex[2726]:         at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:353)
Mai 04 14:38:10 pfxapp0000353 cortex[2726]:         at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:277)
Mai 04 14:38:10 pfxapp0000353 cortex[2726]:         at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$IndexCreationTask.execute(MetaDataCreateIndexService.java:444)
Mai 04 14:38:10 pfxapp0000353 cortex[2726]:         at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:45)
Mai 04 14:38:10 pfxapp0000353 cortex[2726]:         at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:643)
Mai 04 14:38:10 pfxapp0000353 cortex[2726]:         at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:273)
Mai 04 14:38:10 pfxapp0000353 cortex[2726]:         at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:198)
Mai 04 14:38:10 pfxapp0000353 cortex[2726]:         at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:133)
Mai 04 14:38:10 pfxapp0000353 cortex[2726]:         at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150)
Mai 04 14:38:10 pfxapp0000353 cortex[2726]: [info] o.t.c.s.ErrorHandler - POST /api/maintenance/migrate returned 400
Mai 04 14:38:10 pfxapp0000353 cortex[2726]: org.elasticsearch.transport.RemoteTransportException: [VXTecqz][127.0.0.1:9300][indices:admin/create]
Mai 04 14:38:10 pfxapp0000353 cortex[2726]: Caused by: java.lang.IllegalArgumentException: Rejecting mapping update to [cortex_1] as the final mapping would have more than 1 type:
Mai 04 14:38:10 pfxapp0000353 cortex[2726]:         at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:501)
Mai 04 14:38:10 pfxapp0000353 cortex[2726]:         at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:353)
Mai 04 14:38:10 pfxapp0000353 cortex[2726]:         at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:277)
Mai 04 14:38:10 pfxapp0000353 cortex[2726]:         at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$IndexCreationTask.execute(MetaDataCreateIndexService.java:444)
Mai 04 14:38:10 pfxapp0000353 cortex[2726]:         at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:45)
Mai 04 14:38:10 pfxapp0000353 cortex[2726]:         at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:643)
Mai 04 14:38:10 pfxapp0000353 cortex[2726]:         at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:273)
Mai 04 14:38:10 pfxapp0000353 cortex[2726]:         at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:198)
Mai 04 14:38:10 pfxapp0000353 cortex[2726]:         at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:133)
Mai 04 14:38:10 pfxapp0000353 cortex[2726]:         at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150)
Mai 04 14:40:31 pfxapp0000353 cortex[2726]: [info] o.t.c.s.ErrorHandler - GET /api/user/current returned 520
Mai 04 14:40:31 pfxapp0000353 cortex[2726]: org.elasticsearch.transport.RemoteTransportException: [cZhBNdC][127.0.0.1:9300][indices:data/read/search]
Mai 04 14:40:31 pfxapp0000353 cortex[2726]: Caused by: org.elasticsearch.index.IndexNotFoundException: no such index
Mai 04 14:40:31 pfxapp0000353 cortex[2726]:         at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver$WildcardExpres
``` 
UserMgmtCtrl

### Steps to Reproduce
1. Open browser http://.../9001
1. click Update database
1. Browser exib "UserMgmtCtrl"

**Comment by saadkadhi** [comment]
@To-om can you get a look at this one? thx.

**Comment by nadouani** [comment]
@mrmodolo What version of Elasticsearch do you use?

**Comment by mrmodolo** [comment]
Hi!

I used the following procedures to install elasticsearch:
$ wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
$ echo "deb https://artifacts.elastic.co/packages/5.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-5.x.list
$ sudo apt-get update
$ sudo apt install elasticsearch
$ dpkg -l | grep elastic
ii  elasticsearch                                 5.6.9

With version 5.6.9 I was not successful. The solution was to use the Docker Indicates version in its documentation.

**Comment by nadouani** [comment]
Yes, that's why I've asked for the ES version used here

**Comment by mrmodolo** [comment]
Hi!

This is the version I'm using and it worked 100% (running inside Docker)

modolo@pfxapp0000353:~$ curl http://127.0.0.1:9200
{
  "name" : "LmicQ0r",
  "cluster_name" : "hive",
  "cluster_uuid" : "_jCWRghsQtmQ0HF0faMl8w",
  "version" : {
    "number" : "5.6.0",
    "build_hash" : "781a835",
    "build_date" : "2017-09-07T03:09:58.087Z",
    "build_snapshot" : false,
    "lucene_version" : "6.6.0"
  },
  "tagline" : "You Know, for Search"
}

**Comment by shubhamblackstratus** [comment]
Guys, This issue was happened to me as well. Find the below error : 

"org.elasticsearch.transport.RemoteTransportException: [4o8hKW8][127.0.0.1:9300][indices:admin/create]
Caused by: java.lang.IllegalArgumentException: _Rejecting mapping update to [cortex_1] as the final mapping would have more than 1 type_: [**dblist, artifact, data, audit, analyzer, organization, report, job, user, analyzerConfig**]"

I have used ElasticSearch 6.x, so it is expected. @To-om has already suggested links. Now, its already reported bug so we should use ELasticSearch 5.x.  It might help.
