### ISSUE TITLE
Could not logged in to other users and can't find analyzers tabs

### ISSUE THREAD

**Issue by shubhamblackstratus** [TheHive-Project/Cortex#113]
Hi All, 

Working Environment : 

Cortex2.0.4
Elastic4Play1.5.0
Play2.6.12
Elastic4s5.6.0
ElasticSearch client5.6.2
ElasticSearch cluster5.6.10

I am able to access cortex from GUI even, I am also able to create organizations and their respected users. In addition to this, all the analyzers are loaded successfully. 

Issue Definitions : 
1.  Can't find "New Analysis" tab and "Analyzers" tab in GUI
2. Can't login with organizations's "orgadmin" on cortex GUI. 

------------------------------------cortex/application.log---------------------------------------------------
       ---
       MISPWarningLists 1.0
        Mnemonic_pDNS_Closed 3.0
        MaxMind_GeoIP 3.0

```
2018-07-09 14:02:47,844 [INFO] from play.api.Play in main - Application started (Prod)
2018-07-09 14:02:48,679 [INFO] from play.core.server.AkkaHttpServer in main - Listening for HTTP on /0:0:0:0:0:0:0:0:9001

2018-07-09 14:06:30,365 [ERROR] from org.elastic4play.services.auth.MultiAuthSrv in application-akka.actor.default-dispatcher-17 - Authentication failure
org.elastic4play.AuthenticationError: Authentication failure
        at org.thp.cortex.services.LocalAuthSrv.$anonfun$authenticate$1(LocalAuthSrv.scala:39)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:304)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2018-07-09 14:06:30,367 [INFO] from org.thp.cortex.services.ErrorHandler in application-akka.actor.default-dispatcher-17 - POST /api/login returned 401
org.elastic4play.AuthenticationError: Authentication failure
        at org.elastic4play.services.auth.MultiAuthSrv$$anonfun$authenticate$4.applyOrElse(MultiAuthSrv.scala:58)
        at org.elastic4play.services.auth.MultiAuthSrv$$anonfun$authenticate$4.applyOrElse(MultiAuthSrv.scala:55)
        at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:414)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
-------------------------------------------------------------------------------------------------
```

Please help..!

**Comment by nadouani** [comment]
> Can't find "New Analysis" tab and "Analyzers" tab in GUI

This button is only available to users with `analyze` role, so if you don't see it, that means you are logged in with a user doesn't have access to it.

If you can not login, then check your credentials, or login as a super admin, and change your orgadmin's password.

**Comment by shubhamblackstratus** [comment]
I have already created three users. 
1. sshah - superadmin
2. test - analyzer with all access bound to test organization
3. hive_admin - analyzer with all access bound to the_hive project organization. 

But the problem is that I am not able to login with analyzer user profile, I have also shared error logs for that. 

Please find snaps. 
![1](https://user-images.githubusercontent.com/25363342/42440659-03580fc6-8384-11e8-9043-d36c4e6485cd.jpg)
![2](https://user-images.githubusercontent.com/25363342/42440660-0389207a-8384-11e8-895a-392797275b32.jpg)

**Comment by shubhamblackstratus** [comment]
@nadouani  Please help..!

**Comment by nadouani** [comment]
Did you set a password to the `test` user?

**Comment by shubhamblackstratus** [comment]
Yes, I have set it from GUI, thought it did not prompted option to save it but I think it was set automatically. 

For Test user password is test.

**Comment by nadouani** [comment]
Please share a screenshot of the Test organization's users list

**Comment by shubhamblackstratus** [comment]
Adding logs while going to login with test user ....
------------------------------

2018-07-09 14:31:50,884 [ERROR] from org.elastic4play.controllers.Authenticated in application-akka.actor.default-dispatcher-71 - Authentication failure:
        session: AuthenticationError User session not found
        pki: AuthenticationError Certificate authentication is not configured
        key: AuthenticationError Authentication header not found
        basic: AuthenticationError Authentication header not found
        init: AuthenticationError Use of initial user is forbidden because users exist in database
2018-07-09 14:31:50,885 [INFO] from org.thp.cortex.services.ErrorHandler in application-akka.actor.default-dispatcher-71 - GET /api/user/current returned 401
org.elastic4play.AuthenticationError: Authentication failure
        at org.elastic4play.controllers.Authenticated.$anonfun$getContext$4(Authenticated.scala:219)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:304)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2018-07-09 14:31:52,444 [ERROR] from org.elastic4play.services.auth.MultiAuthSrv in application-akka.actor.default-dispatcher-77 - Authentication failure
org.elastic4play.AuthenticationError: Authentication failure
        at org.thp.cortex.services.LocalAuthSrv.$anonfun$authenticate$1(LocalAuthSrv.scala:39)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:304)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2018-07-09 14:31:52,445 [INFO] from org.thp.cortex.services.ErrorHandler in application-akka.actor.default-dispatcher-77 - POST /api/login returned 401
org.elastic4play.AuthenticationError: Authentication failure
        at org.elastic4play.services.auth.MultiAuthSrv$$anonfun$authenticate$4.applyOrElse(MultiAuthSrv.scala:58)
        at org.elastic4play.services.auth.MultiAuthSrv$$anonfun$authenticate$4.applyOrElse(MultiAuthSrv.scala:55)
        at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:414)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
------------------------------------

Please find required snaps : 
![3](https://user-images.githubusercontent.com/25363342/42441072-ffac273a-8384-11e8-8793-aa7f6b427dff.jpg)

**Comment by nadouani** [comment]
So, your `test`has no password saved, otherwise you see a `Edit password` button.

**Comment by shubhamblackstratus** [comment]
But from GUI it always shows new password. I have created other user named test2 but could not find password option. 

Even I have created test3 but every time it did not show me password setting option as well as from GUi I am not able to do so. Every refresh it shows "New Password" option. 

![new password for test3 but could not set at refresh](https://user-images.githubusercontent.com/25363342/42441703-75c4fc3e-8386-11e8-9dd1-0984817fe56f.jpg)
![no option for password set](https://user-images.githubusercontent.com/25363342/42441704-75f3f0ac-8386-11e8-8d08-c1e389ba8be5.jpg)
![refresh](https://user-images.githubusercontent.com/25363342/42441706-76208c48-8386-11e8-8c6e-a7c68e88cfc4.jpg)


 Please help.

Find snaps.

**Comment by nadouani** [comment]
Type the password and hit `ENTER`

**Comment by shubhamblackstratus** [comment]
@nadouani Thank you so much for the help... Sometimes big work is stopped through silly mistakes.  I got user login.  Again thanks and have a great time ahead...!!!!!!! 👍

**Comment by shubhamblackstratus** [comment]
Thanks for helping me...It worked...
