### ISSUE TITLE
Malwares Analyzer for Python 3.4+

### ISSUE THREAD

**Issue by Pcktech** [TheHive-Project/Cortex#159]
### Request Type
Feature Request

### Problem Description
The Malwares.com analyzer uses **dict/list syntax that may require Python 3.7 to function. With Python 3.4 installed Cortex returns:
```
Invalid output
Traceback (most recent call last):
  File "Malwares/malwares.py", line 6, in <module>
    from malwares_api import Api
  File "/usr/cortex/analyzers/analyzers/Malwares/malwares_api.py", line 59
    response = dict(results={**ri['results'], **ra['results']}, response_code=1)
                              ^
SyntaxError: invalid syntax
```

### Request
Utilize Python 3.4+ syntax to process the data successfully.

**Comment by Pcktech** [comment]
Apologies, I'll put this in the cortex analyzer section.
