### ISSUE TITLE
Cortex analyzers fail "invalid output"

### ISSUE THREAD

**Issue by blainedw** [TheHive-Project/Cortex#161]
### Request Type
Bug

### Work Environment

RHEL7
Cortex 
IE 11

### Problem Description
First time running analyzers. Both that I tried had the same problem. CyberProtect and IBMXforce.

### Steps to Reproduce
Use domain myway.com and run

Invalid output
Traceback (most recent call last):
  File "Cyberprotect/CyberprotectAnalyzer.py", line 4, in <module>
    import requests
  File "/usr/lib/python2.6/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/usr/lib/python2.6/site-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/usr/lib/python2.6/site-packages/urllib3/connectionpool.py", line 92
    _blocking_errnos = {errno.EAGAIN, errno.EWOULDBLOCK}
                                    ^
SyntaxError: invalid syntax

**Comment by blainedw** [comment]
Changing Cyberprotect analyzer from python to python3 allowed to analyzer to run successfully. However, it did push the answer to thehive.

Here is the log from thehive:

2019-01-19 20:14:11,789 [INFO] from org.elastic4play.ErrorHandler in application-akka.actor.default-dispatcher-6 - GET /api/stream/X2q6AcEpM65OBzJVOvdn returned 401
org.elastic4play.AuthenticationError: Authentication header not found
        at org.elastic4play.controllers.Authenticated.$anonfun$getFromApiKey$1(Authenticated.scala:131)
        at scala.Option.fold(Option.scala:158)
        at org.elastic4play.controllers.Authenticated.getFromApiKey(Authenticated.scala:131)
        at controllers.StreamCtrl.$anonfun$get$1(StreamCtrl.scala:99)
        at play.api.mvc.ActionBuilderImpl.invokeBlock(Action.scala:482)
        at play.api.mvc.ActionBuilderImpl.invokeBlock(Action.scala:480)
        at play.api.mvc.ActionBuilder$$anon$2.apply(Action.scala:419)
        at connectors.metrics.TimedInterceptor.$anonfun$invoke$2(MetricsModule.scala:119)
        at play.api.mvc.ActionBuilderImpl.invokeBlock(Action.scala:482)
        at play.api.mvc.ActionBuilderImpl.invokeBlock(Action.scala:480)
        at play.api.mvc.ActionBuilder$$anon$2.apply(Action.scala:419)
        at play.api.mvc.Action.$anonfun$apply$2(Action.scala:96)
        at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$4(Accumulator.scala:174)
        at scala.util.Try$.apply(Try.scala:209)

**Comment by Ektoplasma** [comment]
I do not think that the issue is linked to Cortex Project. Your error is related to your Python version 2.6 which has some compatibility issues with connectionpool.
I can only advise you to upgrade to python2.7 at least (some analyzers are developed in Python3). If it is not an option, you might have to solve the compatibility issues by fixing them yourself in the impacted modules.

Related issues:
 - https://github.com/shinken-monitoring/mod-webui/issues/626
 - https://github.com/PyMySQL/PyMySQL/issues/240

**Comment by blainedw** [comment]
Thanks I’ve started doing that, converting them to support Python3.x

DAVID BLAINE, GCIA, CISSP
Information Security Section Manager
General Dynamics Land Systems

6000 East 17 Mile Road, MZ: 435-01-16, Sterling Heights, MI 48313

GDLS Security | p: 586.825.8437 | m: 586-215-4174 | f: 586.825.8606 | blainedw@gdls.com | www.gdls.com



----------------------------------------------------------------------
This is an e-mail from General Dynamics Land Systems. It is for the intended recipient only and may contain confidential and privileged information.  No one else may read, print, store, copy, forward or act in reliance on it or its attachments.  If you are not the intended recipient, please return this message to the sender and delete the message and any attachments from your computer. Your cooperation is appreciated.

**Comment by nadouani** [comment]
Yes, this is definitely another issue related to your python environment.

**Comment by minhanh1234** [comment]
any fix?

I try 
sudo apt-get install -y --no-install-recommends python-pip python2.7-dev python3-pip python3-dev ssdeep libfuzzy-dev libfuzzy2 libimage-exiftool-perl libmagic1 build-essential git libssl-dev

sudo pip install -U pip setuptools && sudo pip3 install -U pip setuptools


still not working
