### ISSUE TITLE
Analyzer Invalid output

### ISSUE THREAD

**Issue by minhanh1234** [TheHive-Project/Cortex#198]
I can't run any analyzers

Ubuntu

- sudo apt-get install -y --no-install-recommends python-pip python2.7-dev python3-pip python3-dev ssdeep libfuzzy-dev libfuzzy2 libimage-exiftool-perl libmagic1 build-essential git libssl-dev

- sudo pip install -U pip setuptools && sudo pip3 install -U pip setuptools

Location of analyzer: /etc/cortex/Cortex-Analyzers/analyzers
nano /etc/cortex/application.conf

## ANALYZERS
analyzer {
  path = ["/etc/cortex/Cortex-Analyzers/analyzers"]
  fork-join-executor {
      parallelism-min = 2
      parallelism-factor = 2.0
      parallelism-max = 4
  }
}

I seem to get a python error, example :
TLP: white
PAP: white
Data Type: url
Data: GitHub.com
Analyzer: Abuse_Finder_2_0

Error: 

Invalid output
Traceback (most recent call last):
  File "Abuse_Finder/abusefinder.py", line 46, in <module>
    AbuseFinderAnalyzer().run()
  File "Abuse_Finder/abusefinder.py", line 42, in run
    self.report({'abuse_finder': self.abuse()})
  File "Abuse_Finder/abusefinder.py", line 31, in abuse
    return ip_abuse(self.get_data())
  File "/usr/local/lib/python2.7/dist-packages/abuse_finder/ip.py", line 42, in ip_abuse
    obj = IPWhois(ip_address)
  File "/usr/local/lib/python2.7/dist-packages/ipwhois/ipwhois.py", line 55, in __init__
    allow_permutations=allow_permutations
  File "/usr/local/lib/python2.7/dist-packages/ipwhois/net.py", line 127, in __init__
    self.address = ip_address(address)
  File "/usr/local/lib/python2.7/dist-packages/ipaddr.py", line 83, in IPAddress
    address)
ValueError: u'github.com' does not appear to be an IPv4 or IPv6 address

Would anyone have any suggestion?

**Comment by runninbutt** [comment]
On the last line it says:
ValueError: u'github.com' does not appear to be an IPv4 or IPv6 address
So you are trying to output a "github.com" to an analyzer which only accepts IP addresses.

**Comment by nadouani** [comment]
Hello @minhanh1234 please check the observable type, and value. `github.com` is not a URL
