### ISSUE TITLE
Cortex Analyzers are running but not visible

### ISSUE THREAD

**Issue by smclinden** [TheHive-Project/Cortex#220]
### Request Type

Bug 

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 19.04
| OS version (client)       | Ubuntu 19.04
| Cortex version / git hash   | 2.1.3
| Package Type              | From source
| Browser type & version    | Chrome 76.0.3809.132/Firefox 68.0.2

### Problem Description
I've installed and built the requirements for the analyzers and responders and have followed all of the latest documentation. The analyzers were installed via git, The user has orgAdmin privileges for the Organization. Ownership and permissions are correct.

The workers appear in the Cortex log but they do not appear on the Analyzers tab of the Organization screen. Running Cortex from the shell shows no error messages.

### Steps to Reproduce

I can't not reproduce it,

**Comment by smclinden** [comment]
Some additional info. I can log into Cortex as the orgAdmin, but when I try to edit the organization, I get the following error:
[error] o.e.c.Authenticated - Authentication failure:
	session: AuthenticationError User session not found
	pki: AuthenticationError Certificate authentication is not configured
	key: AuthenticationError Authentication header not found
	init: AuthenticationError Use of initial user is forbidden because users exist in database
[info] o.t.c.s.ErrorHandler - GET /api/user/current returned 401
org.elastic4play.AuthenticationError: Authentication failure
	at org.elastic4play.controllers.Authenticated.$anonfun$getContext$4(Authenticated.scala:254)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:303)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)

**Comment by nadouani** [comment]
Hello make sure to tell Cortex about the analyzers folder.

If you are still using Cortex 2.x you need to set the path as follow:

```
analyzer.path = ["YOUR_ANALYZERS PATH"]
```

Example:

```
analyzer.path = ["/opt/Cortex-Analyzers/analyzers"]
```
