### ISSUE TITLE
Responders Fail to Execute after upgrading to 3.0 Cortex from 2.3.1

### ISSUE THREAD

**Issue by nicpenning** [TheHive-Project/Cortex#225]
# Official Mailer Responder and our custom Responder fails to execute after upgrade.

### Request Type
Bug 
### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 18
| OS version (client)       |  Windows 10
| Cortex version / git hash   | 3.0.0 / e5dec1e7f936fa4dba4c98b362402422336d2623
| Package Type              | Binary
| Browser type & version    | Chrome

### Problem Description
After upgrading from Cortex 2.3.1 our responders do not work. We created a variation of the Mailer that does not work. The default Mailer responder from https://github.com/TheHive-Project/Cortex-Analyzers/releases/tag/2.1.8 **does not work either.**

### Steps to Reproduce
1. Upgrade Cortex to 3.0.0
2. Refresh responders / supply config details if needed
3. Run Responder
4. Fails with no output (see below for specific error message)

### Complementary information
![image](https://user-images.githubusercontent.com/5582679/64824756-98f16d80-d580-11e9-8b93-e1bb13a8726d.png)

From Cortex UI:
![image](https://user-images.githubusercontent.com/5582679/64824888-06050300-d581-11e9-835c-77b6fb2a0ab8.png)

Report
{
  "errorMessage": "no output",
  "input": null,
  "success": false
}

I am tempted to roll back and ensure it was from the upgrade, but I am pretty confident something isn't quite right here.

Let me know if there are other details I can provide.

Thanks!

**Comment by nicpenning** [comment]
Update with Cortex Error log from /var/log/cortex/application.log

2019-09-13 13:50:25,675 [INFO] from org.thp.cortex.services.JobSrv in application-akka.actor.default-dispatcher-11 - Job cache is disabled
2019-09-13 13:50:26,762 [INFO] from org.thp.cortex.services.AuditActor in application-akka.actor.default-dispatcher-50 - Register new listener for job 8azjKm0BlrkNPK-vp8KP (Actor[akka://application/temp/$n])
2019-09-13 13:50:26,881 [INFO] from org.thp.cortex.services.AuditActor in application-akka.actor.default-dispatcher-13 - Job 8azjKm0BlrkNPK-vp8KP has be updated (JsDefined("InProgress"))
2019-09-13 13:50:26,881 [INFO] from org.thp.cortex.services.ProcessJobRunnerSrv in application-akka.actor.default-dispatcher-18 - Execute /etc/cortex/customs/responders/Mailer/mailer.py in /etc/cortex/customs/responders, timeout is 30 minutes
2019-09-13 13:50:26,930 [INFO] from org.thp.cortex.services.ProcessJobRunnerSrv in Thread-74 -   Job 8azjKm0BlrkNPK-vp8KP: Traceback (most recent call last):
2019-09-13 13:50:26,931 [INFO] from org.thp.cortex.services.ProcessJobRunnerSrv in Thread-74 -   Job 8azjKm0BlrkNPK-vp8KP:   File "/etc/cortex/customs/responders/Mailer/mailer.py", line 62, in <module>
2019-09-13 13:50:26,931 [INFO] from org.thp.cortex.services.ProcessJobRunnerSrv in Thread-74 -   Job 8azjKm0BlrkNPK-vp8KP:     Mailer().run()
2019-09-13 13:50:26,931 [INFO] from org.thp.cortex.services.ProcessJobRunnerSrv in Thread-74 -   Job 8azjKm0BlrkNPK-vp8KP:   File "/etc/cortex/customs/responders/Mailer/mailer.py", line 12, in __init__
2019-09-13 13:50:26,931 [INFO] from org.thp.cortex.services.ProcessJobRunnerSrv in Thread-74 -   Job 8azjKm0BlrkNPK-vp8KP:     Responder.__init__(self)
2019-09-13 13:50:26,931 [INFO] from org.thp.cortex.services.ProcessJobRunnerSrv in Thread-74 -   Job 8azjKm0BlrkNPK-vp8KP:   File "/usr/local/lib/python2.7/dist-packages/cortexutils/responder.py", line 11, in __init__
2019-09-13 13:50:26,931 [INFO] from org.thp.cortex.services.ProcessJobRunnerSrv in Thread-74 -   Job 8azjKm0BlrkNPK-vp8KP:     Worker.__init__(self)
2019-09-13 13:50:26,931 [INFO] from org.thp.cortex.services.ProcessJobRunnerSrv in Thread-74 -   Job 8azjKm0BlrkNPK-vp8KP:   File "/usr/local/lib/python2.7/dist-packages/cortexutils/worker.py", line 20, in __init__
2019-09-13 13:50:26,931 [INFO] from org.thp.cortex.services.ProcessJobRunnerSrv in Thread-74 -   Job 8azjKm0BlrkNPK-vp8KP:     self._input = json.load(self.fpinput)
2019-09-13 13:50:26,931 [INFO] from org.thp.cortex.services.ProcessJobRunnerSrv in Thread-74 -   Job 8azjKm0BlrkNPK-vp8KP:   File "/usr/lib/python2.7/json/__init__.py", line 291, in load
2019-09-13 13:50:26,931 [INFO] from org.thp.cortex.services.ProcessJobRunnerSrv in Thread-74 -   Job 8azjKm0BlrkNPK-vp8KP:     **kw)
2019-09-13 13:50:26,931 [INFO] from org.thp.cortex.services.ProcessJobRunnerSrv in Thread-74 -   Job 8azjKm0BlrkNPK-vp8KP:   File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
2019-09-13 13:50:26,931 [INFO] from org.thp.cortex.services.ProcessJobRunnerSrv in Thread-74 -   Job 8azjKm0BlrkNPK-vp8KP:     return _default_decoder.decode(s)
2019-09-13 13:50:26,931 [INFO] from org.thp.cortex.services.ProcessJobRunnerSrv in Thread-74 -   Job 8azjKm0BlrkNPK-vp8KP:   File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
2019-09-13 13:50:26,931 [INFO] from org.thp.cortex.services.ProcessJobRunnerSrv in Thread-74 -   Job 8azjKm0BlrkNPK-vp8KP:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2019-09-13 13:50:26,931 [INFO] from org.thp.cortex.services.ProcessJobRunnerSrv in Thread-74 -   Job 8azjKm0BlrkNPK-vp8KP:   File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
2019-09-13 13:50:26,931 [INFO] from org.thp.cortex.services.ProcessJobRunnerSrv in Thread-74 -   Job 8azjKm0BlrkNPK-vp8KP:     raise ValueError("No JSON object could be decoded")
2019-09-13 13:50:26,931 [INFO] from org.thp.cortex.services.ProcessJobRunnerSrv in Thread-74 -   Job 8azjKm0BlrkNPK-vp8KP: ValueError: No JSON object could be decoded
2019-09-13 13:50:27,894 [INFO] from org.thp.cortex.services.AuditActor in application-akka.actor.default-dispatcher-13 - Job 8azjKm0BlrkNPK-vp8KP has be updated (JsDefined("Failure"))
2019-09-13 13:50:27,895 [INFO] from org.thp.cortex.services.JobSrv in application-akka.actor.default-dispatcher-18 - Job 8azjKm0BlrkNPK-vp8KP has finished with status Failure

**Comment by nicpenning** [comment]
The issue was that I had cortexutils 1.3 still even though I ran: sudo pip install -U cortexutils && sudo pip3 install -U cortexutils

The gotcha was that pip and pip3 were pointing to  python 3.6.

To fix this run this command instead:
 sudo pip2 install -U cortexutils && sudo pip3 install -U cortexutil
