### ISSUE TITLE
Mailer responder fails due to akka.pattern.AskTimeoutException

### ISSUE THREAD

**Issue by hodoken** [TheHive-Project/Cortex#232]
### Request Type
Bug

### Work Environment
| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | CentOS
| OS version (client)       | 10
| Cortex version / git hash   | 3.0.0-1
| Package Type              | Binary
| Browser type & version    | Chrome 77.0.3865.120

### Problem Description
This is my first time using any Responder in Cortex. I enabled and configured mailer responder. Whenever I run the mailer responder against an open (thehive) case, it would error out. Complementary information contasins a snippet of the cortex log relevant to the issue.

### Steps to Reproduce
1. Using Amazon 2 AMI to install TheHive and Cortex
2. Configured Cortex application.conf and added responder.urls along with copying `fork-join-executor` and it's elements from analyzer section in conf file of Cortex 
3. Enabled and configured the Mailer responder in Cortex UI, under Responder config tab (Global Configuration was not touched):
	- from: <sender_email>
	- smtp_host: smtp.gmail.com
	- smtp_port:587
4. Run the mailer responder from any open case of TheHive

### Complementary information
```
2019-10-16 17:11:19,579 [INFO] from org.thp.cortex.services.AuditActor in application-akka.actor.default-dispatcher-2 - Register new listener for job 9seJ1W0BpTRwyqguxD7O (Actor[akka://application/temp/$k])
2019-10-16 17:12:19,590 [INFO] from org.thp.cortex.services.AuditActor in application-akka.actor.default-dispatcher-5 - Unregister listener for job 9seJ1W0BpTRwyqguxD7O (Actor[akka://application/temp/$k])
2019-10-16 17:12:19,590 [INFO] from org.thp.cortex.services.ErrorHandler in application-akka.actor.default-dispatcher-3 - GET /api/job/9seJ1W0BpTRwyqguxD7O/waitreport?atMost=1%20minute returned 500
akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://application/user/audit#-735547229]] after [60000 ms]. Message of type [org.thp.cortex.services.AuditActor$Register]. A typical reason for `AskTimeoutException` is that the recipient actor didn't send a reply.
        at akka.pattern.PromiseActorRef$.$anonfun$defaultOnTimeout$1(AskSupport.scala:635)
        at akka.pattern.PromiseActorRef$.$anonfun$apply$1(AskSupport.scala:650)
        at akka.actor.Scheduler$$anon$4.run(Scheduler.scala:205)
        at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:874)
        at scala.concurrent.BatchingExecutor.execute(BatchingExecutor.scala:113)
        at scala.concurrent.BatchingExecutor.execute$(BatchingExecutor.scala:107)
        at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:872)
        at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(LightArrayRevolverScheduler.scala:328)
        at akka.actor.LightArrayRevolverScheduler$$anon$3.executeBucket$1(LightArrayRevolverScheduler.scala:279)
        at akka.actor.LightArrayRevolverScheduler$$anon$3.nextTick(LightArrayRevolverScheduler.scala:283)
        at akka.actor.LightArrayRevolverScheduler$$anon$3.run(LightArrayRevolverScheduler.scala:235)
        at java.lang.Thread.run(Thread.java:748)
2019-10-16 17:12:20,330 [INFO] from org.thp.cortex.services.ProcessJobRunnerSrv in application-responder-44 - Timeout reached, killing process
2019-10-16 17:12:20,395 [INFO] from org.thp.cortex.services.AuditActor in application-akka.actor.default-dispatcher-3 - Job 9seJ1W0BpTRwyqguxD7O has be updated (JsDefined("Failure"))
2019-10-16 17:12:20,396 [INFO] from org.thp.cortex.services.JobSrv in application-akka.actor.default-dispatcher-5 - Job 9seJ1W0BpTRwyqguxD7O has finished with status Failure
```

**Comment by nadouani** [comment]
The error looks like your responder fails by reaching the timeout. You need to understand why:
- you have set a small timeout 
- your have a connectivity issues
