### ISSUE TITLE
Cortex "Error: version conflict, document already exists"

### ISSUE THREAD

**Issue by ZSZ72** [TheHive-Project/Cortex#236]
### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| OS version (client)       | 10
| Cortex version / git hash   | Fresh install from DEB
| Package Type              | DEB
| Browser type & version    | Firefox

### Problem Description
After updating database in Cortex, when the create administrator account pages comes up, nothing happens when I press create after filling up the credentials. I tried refreshing the page but then "Error: user init not found" comes up. The logs show that there is a version conflict, document already exists so tried deleting the Cortex instance and elasticsearch to re-initiate Cortex but still unable to create administrator account. Also tried starting over from the very beginning by installing everything again but still facing the same issue. 

Had done this before and everything was working fine until recently. 

### Steps to Reproduce
1. Install the new instance of Cortex and ElasticSearch

### Complementary information
2019-12-03 06:09:34,717 [INFO] from org.thp.cortex.services.ErrorHandler in application-akka.actor.default-dispatcher-5 - POST /api/user returned 400
org.elastic4play.ConflictError: [doc][cortex]: version conflict, document already exists (current version [1])
        at org.elastic4play.database.DBConfiguration.$anonfun$execute$2(DBConfiguration.scala:146)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by nadouani** [comment]
Is this a fresh install?

**Comment by ZSZ72** [comment]
Yes

**Comment by ZSZ72** [comment]
Is there any update on this? Has anyone else encountered the same error or managed to install the latest integration of Hive? If yes, please do share how you managed to resolve the issue.

**Comment by nadouani** [comment]
Can you drop your DB and retry? I suppose you have no data in there?

**Comment by ZSZ72** [comment]
Have retried after dropping the DB, still getting the same error. 

In the web browser, after inputting the login, name and password to create administrator account, the page does not get redirected to the login page after clicking "Create". It remains at a standstill at the "Create Administrator Account" page regardless of how many times I press "Create" or how much time is given to the page to load. The logs show that there is a version conflict, document already exists. 

In previous attempts, had tried the following:
- Delete the database and retry
- Purge
- Uninstall everything and bringing in up again
- Start complete installation in new machine
- Change the version of Elastic Search DB
- Install each version manually one by one
- Purge and install previous version

All the attempts have given the same error mentioned above.

**Comment by nadouani** [comment]
`The logs show that there is a version conflict, document already exists.` This means that your Cortex is finding the data you try to create.

What's the result of 

```
curl http://localhost:9200/_cat/indices
```

**Comment by ZSZ72** [comment]
The result is as follows:

yellow open cortex_4 I35PZd9qTt2gnXgWiaqZGw 5 1 1 0 5.3kb 5.3kb

**Comment by nadouani** [comment]
And what's the result of 
```
curl http://localhost:9200/cortex_4/doc/_count\?q\=relations:user
```
I just want to check you have users on your db

**Comment by ZSZ72** [comment]
The result is as follows:

{"count":0,"_shards":{"total":5,"successful":5,"skipped":0,"failed":0}}

**Comment by mbonneralagen** [comment]
Quick update, if you don't set your username to cortex it should work, I'm not exactly sure the reason, my guess is that there's an org already called cortex and when it tries to create that user it throws the error.
