### ISSUE TITLE
Analyzers - Failure

### ISSUE THREAD

**Issue by stoksoz1** [TheHive-Project/Cortex#252]
On analyzers section we are getting this eror;

`Traceback (most recent call last):  File "/usr/lib/python3.7/sre_parse.py", line 1021, in parse_template    this = chr(ESCAPES[this][1])KeyError: '\\s'During handling of the above exception, another exception occurred:Traceback (most recent call last):  File "/etc/cortex/Cortex-Analyzers/analyzers/Abuse_Finder/abusefinder.py", line 9, in <module>    from abuse_finder import domain_abuse, ip_abuse, \  File "/usr/local/lib/python3.7/dist-packages/abuse_finder/__init__.py", line 2, in <module>    from .domain import domain_abuse  File "/usr/local/lib/python3.7/dist-packages/abuse_finder/domain.py", line 3, in <module>    from pythonwhois.net import get_whois_raw  File "/usr/local/lib/python3.7/dist-packages/pythonwhois/__init__.py", line 1, in <module>    from . import net, parse  File "/usr/local/lib/python3.7/dist-packages/pythonwhois/parse.py", line 363, in <module>    registrant_regexes = [preprocess_regex(regex) for regex in registrant_regexes]  File "/usr/local/lib/python3.7/dist-packages/pythonwhois/parse.py", line 363, in <listcomp>    registrant_regexes = [preprocess_regex(regex) for regex in registrant_regexes]  File "/usr/local/lib/python3.7/dist-packages/pythonwhois/parse.py", line 205, in preprocess_regex    regex = re.sub(r"\\s\*\(\?P<([^>]+)>\.\+\)", r"\s*(?P<\1>\S.*)", regex)  File "/usr/lib/python3.7/re.py", line 192, in sub    return _compile(pattern, flags).sub(repl, string, count)  File "/usr/lib/python3.7/re.py", line 309, in _subx    template = _compile_repl(template, pattern)  File "/usr/lib/python3.7/re.py", line 300, in _compile_repl    return sre_parse.parse_template(repl, pattern)  File "/usr/lib/python3.7/sre_parse.py", line 1024, in parse_template    raise s.error('bad escape %s' % this, len(this))re.error: bad escape \s at position 0`

**Comment by KRUXLEX** [comment]
What analyzer?

**Comment by asucrews** [comment]
This looks to bue Abuse_Finder, i am getting the same error

/opt/Cortex-Analyzers/analyzers/Abuse_Finder/abusefinder.py 97.97.97.97
Traceback (most recent call last):
  File "/usr/lib/python3.8/sre_parse.py", line 1039, in parse_template
    this = chr(ESCAPES[this][1])
KeyError: '\\s'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/Cortex-Analyzers/analyzers/Abuse_Finder/abusefinder.py", line 9, in <module>
    from abuse_finder import domain_abuse, ip_abuse, \
  File "/usr/local/lib/python3.8/dist-packages/abuse_finder/__init__.py", line 2, in <module>
    from .domain import domain_abuse
  File "/usr/local/lib/python3.8/dist-packages/abuse_finder/domain.py", line 3, in <module>
    from pythonwhois.net import get_whois_raw
  File "/usr/local/lib/python3.8/dist-packages/pythonwhois/__init__.py", line 1, in <module>
    from . import net, parse
  File "/usr/local/lib/python3.8/dist-packages/pythonwhois/parse.py", line 363, in <module>
    registrant_regexes = [preprocess_regex(regex) for regex in registrant_regexes]
  File "/usr/local/lib/python3.8/dist-packages/pythonwhois/parse.py", line 363, in <listcomp>
    registrant_regexes = [preprocess_regex(regex) for regex in registrant_regexes]
  File "/usr/local/lib/python3.8/dist-packages/pythonwhois/parse.py", line 205, in preprocess_regex
    regex = re.sub(r"\\s\*\(\?P<([^>]+)>\.\+\)", r"\s*(?P<\1>\S.*)", regex)
  File "/usr/lib/python3.8/re.py", line 208, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/usr/lib/python3.8/re.py", line 325, in _subx
    template = _compile_repl(template, pattern)
  File "/usr/lib/python3.8/re.py", line 316, in _compile_repl
    return sre_parse.parse_template(repl, pattern)
  File "/usr/lib/python3.8/sre_parse.py", line 1042, in parse_template
    raise s.error('bad escape %s' % this, len(this))
re.error: bad escape \s at position 0
