### ISSUE TITLE
Authentication error after migrating from 2.1.3 to 3.0.1

### ISSUE THREAD

**Issue by masual** [TheHive-Project/Cortex#270]
### Request Type
Bug 
### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| OS version (client)       | 16.04, Kubernetes 1.14
| Cortex version / git hash   | 2.1.3->3.0.1
| Package Type              | Docker

### Problem Description
After changing the Docker image version to 3.0.1 and modifying the configuration according to [this guide](https://github.com/TheHive-Project/CortexDocs/blob/master/migration_guide.md), it is not possible to login to Cortex. We are using LDAP integration, and it was working ok with previous version. Checking the logs, there are some warnings and the attached Error. The issue seems related to Cortex not being able to perform an API request to `/api/user/current`.

### Steps to Reproduce
1. Migrate a working Cortex setup running on 2.1.3 to 3.0.1 version

### Complementary information

> [error] o.e.s.a.MultiAuthSrv - Authentication failure
org.elastic4play.AuthenticationError: Authentication using API key is not supported
        at org.elastic4play.services.AuthSrv.authenticate(UserSrv.scala:50)
        at org.elastic4play.services.AuthSrv.authenticate$(UserSrv.scala:49)
        at org.elastic4play.services.auth.LdapAuthSrv.authenticate(LdapAuthSrv.scala:99)
        at org.elastic4play.services.auth.MultiAuthSrv.$anonfun$authenticate$3(MultiAuthSrv.scala:58)
        at org.elastic4play.services.auth.MultiAuthSrv$$anonfun$$nestedInanonfun$forAllAuthProvider$1$1.applyOrElse(MultiAuthSrv.scala:43)
        at org.elastic4play.services.auth.MultiAuthSrv$$anonfun$$nestedInanonfun$forAllAuthProvider$1$1.applyOrElse(MultiAuthSrv.scala:41)
        at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:417)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
[info] o.t.c.s.ErrorHandler - GET /api/user/current returned 500

**Comment by AngelaSvoykina** [comment]
Faced the same issue, maybe any news on this one?
