### ISSUE TITLE
[bug] GET /api/user/current fails with 500

### ISSUE THREAD

**Issue by jakubgs** [TheHive-Project/Cortex#306]
### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 20.04
| Cortex version / git hash   | `3.0.1-1`
| Package Type              | Binary
| ElasticSearch | `7.8.0`

### Problem Description
I started Cortex with a very standard config based on [the provided one](https://github.com/TheHive-Project/Cortex/blob/3.0.1/conf/application.sample) in which essentially I just changed the `url` and `index`. After [creating the `cortex_4` index manually](https://github.com/TheHive-Project/Cortex/issues/305) I tried opening the Web UI but all I got were failed `GET /api/user/current` requests receiving `500` errors:
```
{
  "type": "com.fasterxml.jackson.databind.exc.MismatchedInputException",
  "message": "Cannot deserialize instance of `long` out of START_OBJECT token\n at [Source: (String)\"{\"took\":6,\"timed_out\":false,\"_shards\":{\"total\":3,\"successful\":3,\"skipped\":0,\"failed\":0},\"hits\":{\"total\":{\"value\":0,\"relation\":\"eq\"},\"max_score\":null,\"hits\":[]}}\"; line: 1, column: 105] (through reference chain: com.sksamuel.elastic4s.http.search.SearchResponse[\"hits\"]->com.sksamuel.elastic4s.http.search.SearchHits[\"total\"])"
}
```
Which shows up in logs as:
```
[info] o.t.c.s.ErrorHandler [|] GET /api/user/current returned 500
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `long` out of START_OBJECT token
 at [Source: (String)"{"took":5,"timed_out":false,"_shards":{"total":3,"successful":3,"skipped":0,"failed":0},"hits":{"total":{"value":0,"relation":"eq"},"max_score":null,"hits":[]}}"; line: 1, column: 105] (through reference chain: com.sksamuel.elastic4s.http.search.SearchResponse["hits"]->com.sksamuel.elastic4s.http.search.SearchHits["total"])
        at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
        at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1342)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1138)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1092)
        at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$LongDeserializer._parseLong(NumberDeserializers.java:593)
        at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$LongDeserializer.deserialize(NumberDeserializers.java:557)
        at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$LongDeserializer.deserialize(NumberDeserializers.java:535)
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:530)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:528)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:417)
```
Which I have no idea what I'm supposed to do about.

**Comment by To-om** [comment]
You must not create the index manually. This the reason of this problem.

**Comment by jakubgs** [comment]
The index was not being created because `3.0.1-1` does not support ElasticSearch `7.8.0`.

I was doubly confused because `3.1.0-RC1` which is supposed to support ES 7 was also not creating it, but that was a bug.
