### ISSUE TITLE
Enable Oauth2 with Office365

### ISSUE THREAD

**Issue by Kn-ut99** [TheHive-Project/Cortex#322]
# Enable Oauth2 with Office365

### Request Type
Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 18.04
| OS version (client)       | Any
| Cortex version / git hash   | 3.1.0
| Package Type              | Ubuntu package from official repo
| Browser type & version    | Firefox

### Problem Description
I was able to leverage our Office365 tenant for Oauth2 login in TheHive4 by following the [documentation](https://github.com/TheHive-Project/TheHiveDocs/blob/master/TheHive4/Administration/Authentication.md), however I cannot seem to find the right settings for Cortex.
It seems that Cortex 3.x use a somewhat similar Oauth2 approach as TheHive 3.x. which doesn't include an 0ffice365 config example in its [documentation.](https://github.com/TheHive-Project/TheHiveDocs/blob/master/admin/configuration.md#32-oauth2openid-connect)

### Steps to Reproduce
1. Install Cortex 3.1.0

1. Follow Oauth configuration per [Cortex documentation](https://github.com/TheHive-Project/CortexDocs/blob/master/admin/admin-guide.md#OAuth2openid-connect) while adapting the settings for Office365
```
auth {
     provider = [local, oauth2]
     [...]
    oauth2 {
                clientId: "[REDACTED]"
                clientSecret: "[REDACTED]"
                redirectUri: "https://[REDACTED]/api/ssoLogin"
                responseType: code
                grantType: "authorization_code"
                authorizationUrl: "https://login.microsoftonline.com/[REDACTED]/oauth2/v2.0/authorize"
                authorizationHeader: "Bearer "
                tokenUrl: "https://login.microsoftonline.com/[REDACTED]/oauth2/v2.0/token"
                userUrl: "https://graph.microsoft.com/v1.0/me"
                scope: ["User.Read"]
                userIdField: "mail"

    sso {
                autocreate: false
                autoupdate: false
                mapper: "simple"
                attributes {
                  login: "login"
                  name: "displayName"
                  roles: "role"
                  }
                defaultRoles: ["read", "analyze"]
                defaultOrganization: "[REDACTED]"
                 }
}
```
1. Restart Cortex service
1. Try to login with SSO --> you'll get an error : `{"type":"AuthenticationError","message":"Authentication failure"}`
1. Check Cortex logs : 
```
2020-11-25 16:00:56,459 [INFO] from org.thp.cortex.services.ErrorHandler in application-akka.actor.default-dispatcher-12 - GET /api/ssoLogin?code=0.AAAAwyMriWLWF0Sdydr[...]OjedED3_JcgAA&state=9b101cb8-8050-4aea-8589-160edf930ba3&session_state=ecff93ba-0f91-46b1-adaa-28c213e522b7 returned 401
org.elastic4play.AuthenticationError: Authentication failure
        at org.elastic4play.services.auth.MultiAuthSrv$$anonfun$authenticate$6.applyOrElse(MultiAuthSrv.scala:70)
        at org.elastic4play.services.auth.MultiAuthSrv$$anonfun$authenticate$6.applyOrElse(MultiAuthSrv.scala:67)
        at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:417)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:56)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:93)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:93)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

### Complementary information
The Cortex documentation doesn't say it is compatible with Office365, maybe the answer is that it is not yet implemented.
Any insight would be appreciated.

**Comment by Kn-ut99** [comment]
Ok so I'm an idiot, it **is** working when you don't mess up the configuration with a faulty Ansible deployment playbook :)
The configuration I posted originally is **valid** for Office365, you just have to replace the [REDACTED] parts with your TenantID, AppID and SecretID to make this work.
I'm closing this request.

**Comment by arnydo** [comment]
@Kn-ut99 I have the same issue, however, my config looks identical to yours (with the appropriate info in the `REDACTED` fields.

Did you do anything additional to resolve?

**Comment by Kn-ut99** [comment]
@arnydo this is still working here with the exact same configuration.
Just make sur you use the same name/ip to connect to cortex as the url configured in `redirectUri`. I made the mistake once to not connect with the fqdn of our cortex instance and SSO wouldn't work. (`https://cortex instead` of `https://cortex.mycompany.domain`)

**Comment by arnydo** [comment]
@Kn-ut99 I double checked to make sure this is true. As far as I can tell everything matches up but still have an auth failed. The hive oauth works fine.

**Comment by Kn-ut99** [comment]
It is hard to help if you do not provide more information (logs & conf).

**Comment by arnydo** [comment]
@Kn-ut99 it's identical to what you shared except for my values for client/secret, tenant, etc. I'll share a snippet tomorrow. Thanks.

**Comment by arnydo** [comment]
@Kn-ut99  here is what I have configured.

```
        oauth2 {
                clientId: "[CLIENTID]"
                clientSecret: "[SECRET]"
                redirectUri: "https://[FQDN]/api/ssoLogin"
                responseType: code
                grantType: "authorization_code"
                authorizationUrl: "https://login.microsoftonline.com/[TENANT]/oauth2/v2.0/authorize"
                authorizationHeader: "Bearer "
                tokenUrl: "https://login.microsoftonline.com/[TENANT]/oauth2/v2.0/token"
                userUrl: "https://graph.microsoft.com/v1.0/me"
                scope: ["User.Read"]
                userIdField: "mail"
}
```

So it looks like it may be authenticating with Azure okay but something else on Cortex throwing the failure?

```
2021-03-23 08:00:07,694 [INFO] from org.thp.cortex.services.ErrorHandler in application-akka.actor.default-dispatcher-5028 - GET /api/ssoLogin?code=XXXXXXXXXX&state=XXXXXX&session_state=XXXXXX returned 401
org.elastic4play.AuthenticationError: Authentication failure
        at org.elastic4play.services.auth.MultiAuthSrv$$anonfun$authenticate$6.applyOrElse(MultiAuthSrv.scala:70)
        at org.elastic4play.services.auth.MultiAuthSrv$$anonfun$authenticate$6.applyOrElse(MultiAuthSrv.scala:67)
        at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:417)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:56)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:93)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:93)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
```

**Comment by arnydo** [comment]
Just compared the setup with TheHive (Config and Azure settings). They are identical, yet, Cortex throws the same error you showed above.

**Comment by Kn-ut99** [comment]
> @Kn-ut99 here is what I have configured.
> 
> ```
>         oauth2 {
>                 clientId: "[CLIENTID]"
>                 clientSecret: "[SECRET]"
>                 redirectUri: "https://[FQDN]/api/ssoLogin"
>                 responseType: code
>                 grantType: "authorization_code"
>                 authorizationUrl: "https://login.microsoftonline.com/[TENANT]/oauth2/v2.0/authorize"
>                 authorizationHeader: "Bearer "
>                 tokenUrl: "https://login.microsoftonline.com/[TENANT]/oauth2/v2.0/token"
>                 userUrl: "https://graph.microsoft.com/v1.0/me"
>                 scope: ["User.Read"]
>                 userIdField: "mail"
> }
> ```
> 
> So it looks like it may be authenticating with Azure okay but something else on Cortex throwing the failure?
> 
> ```
> 2021-03-23 08:00:07,694 [INFO] from org.thp.cortex.services.ErrorHandler in application-akka.actor.default-dispatcher-5028 - GET /api/ssoLogin?code=XXXXXXXXXX&state=XXXXXX&session_state=XXXXXX returned 401
> org.elastic4play.AuthenticationError: Authentication failure
>         at org.elastic4play.services.auth.MultiAuthSrv$$anonfun$authenticate$6.applyOrElse(MultiAuthSrv.scala:70)
>         at org.elastic4play.services.auth.MultiAuthSrv$$anonfun$authenticate$6.applyOrElse(MultiAuthSrv.scala:67)
>         at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:417)
>         at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
>         at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
>         at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:56)
>         at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:93)
>         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
>         at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
>         at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:93)
>         at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
>         at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
>         at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
>         at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
>         at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
>         at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
> ```

Can you post the `sso { [...] }` part of your config file ?
I had this error when my cortex config file was messed up.
Check if you do not have some double entries/config in that file.

**Comment by arnydo** [comment]
Here is the SSO section. Again, same as yours but still getting the same error.

```
sso {
        autocreate = false
        autoupdate = false
        autologin = false
        mapper: "simple"
        attributes {
          login = "login"
          name = "displayName"
          role = "role"
        }
        defaultRoles = ["read", "analyze"]
        defaultOrganization = "[ORG]"
    }
```
