### ISSUE TITLE
[Bug] TheHive+Cortex: Unable to run analyzer [...] on observable: [...]

### ISSUE THREAD

**Issue by 0cta** [TheHive-Project/Cortex#336]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | RedHat Enterprise Linux
| OS version (client)       | 7
| TheHive version / git hash   | 3.5.0-1
| Cortex version           |  3.1.0-1
| Package Type              | Both RPM
| Browser type & version    |  FF/Chrome latest stable
| Reverse Proxy          |  Nginx 1.16.1

### Problem Description
Running Cortex analyzers from a case observable's context is not working due to an error in the communication with Cortex.
The popup error states "Unable to run analyzer [name of any analyzer] on observable: [...]". Therefore, no results are retrieved.

### Steps to Reproduce
1. Add observable to any case, e.g. a Domain
2. Run any analyzer on the added observable that matches its type, e.g. VirusTotal_GetReport_3_0
3. Receive error message: _Unable to run analyzer VirusTotal_GetReport_3_0 for observable: whatever.com_

### Complementary information
Cortex itself is up and running perfectly fine, the analyzers are able to successfully enrich information provided to them via Cortex WebUI. Both TheHive and Cortex share the same secret.

Below you'll find what I've deemed relevant information. If you require more info, please tell me. Its my first bug report.

**Excerpt from /var/log/cortex/application.log after trying to fire an analyzer from TheHive:**

> 2021-02-04 16:42:03,398 [DEBUG] from org.elasticsearch.client.RestClient in I/O dispatcher 3 - request [POST http://127.0.0.1:9200/cortex_5/_search] returned [HTTP/1.1 200 OK]
> 2021-02-04 16:42:03,398 [DEBUG] from com.sksamuel.elastic4s.http.JavaClient in I/O dispatcher 3 - Http Response Response{requestLine=POST /cortex_5/_search HTTP/1.1, host=http://127.0.0.1:9200, response=HTTP/1.1 200 OK}
> 2021-02-04 16:42:03,398 [DEBUG] from org.apache.http.impl.nio.client.InternalIODispatch in I/O dispatcher 3 - http-outgoing-2 [ACTIVE] [content length: 160; pos: 160; completed: true]
> 2021-02-04 16:42:03,398 [DEBUG] from com.sksamuel.elastic4s.ResponseHandler$ in application-akka.actor.default-dispatcher-21717 - Attempting to unmarshall response to com.sksamuel.elastic4s.requests.searches.SearchResponse
> 2021-02-04 16:42:03,398 [DEBUG] from com.sksamuel.elastic4s.ResponseHandler$ in application-akka.actor.default-dispatcher-21717 - {"took":0,"timed_out":false,"_shards":{"total":5,"successful":5,"skipped":0,"failed":0},"hits":{"total":{"value":0,"relation":"eq"},"max_score":null,"hits":[]}}
> **2021-02-04 16:42:03,398 [INFO] from org.thp.cortex.services.ErrorHandler in application-akka.actor.default-dispatcher-21692 - GET /api/analyzer/_search returned 404**
> **org.elastic4play.NotFoundError: worker _search not found**
>         at org.thp.cortex.services.WorkerSrv.$anonfun$getForOrganization$2(WorkerSrv.scala:82)
>         at scala.Option.getOrElse(Option.scala:189)
>         at org.thp.cortex.services.WorkerSrv.$anonfun$getForOrganization$1(WorkerSrv.scala:82)
>         at scala.util.Success.$anonfun$map$1(Try.scala:255)
>         at scala.util.Success.map(Try.scala:213)
>         at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
>         at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
>         at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
>         at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
>         at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:56)
>         at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:93)
>         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
>         at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
>         at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:93)
>         at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
>         at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
>         at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
>         at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
>         at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
>         at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)

**Excerpt from /var/log/thehive/application.log**

> Request DefaultFullHttpRequest(decodeResult: success, version: HTTP/1.1, content: UnpooledHeapByteBuf(freed))
> POST /api/analyzer/_search HTTP/1.1
> Content-Type: application/json
> Authorization: Bearer REMOVED
> content-length: 77
> host: REMOVED
> accept: */*
> user-agent: AHC/2.1
> 
> Response DefaultHttpResponse(decodeResult: success, version: HTTP/1.1)
> HTTP/1.1 301 Moved Permanently
> Server: nginx/1.14.1
> Date: Thu, 04 Feb 2021 15:58:53 GMT
> Content-Type: text/html
> Content-Length: 185
> Connection: keep-alive
> Location: https://REMOVED/api/analyzer/_search
> 
> 2021-02-04 16:58:45,334 [DEBUG] from play.shaded.ahc.org.asynchttpclient.netty.handler.intercept.Redirect30xInterceptor in AsyncHttpClient-9-2 - Redirecting to https://REMOVED/api/analyzer/_search
> 2021-02-04 16:58:45,334 [DEBUG] from play.shaded.ahc.org.asynchttpclient.netty.handler.intercept.Redirect30xInterceptor in AsyncHttpClient-9-2 - Sending redirect to https://REMOVED/api/analyzer/_search
> 2021-02-04 16:58:45,334 [DEBUG] from play.shaded.ahc.org.asynchttpclient.netty.request.NettyRequestSender in AsyncHttpClient-9-2 - Using pooled Channel '[id: 0x9016d965, L:/10.58.228.234:33394 - R:REMOVED/10.58.228.232:4
> 43]' for 'GET' to 'https://REMOVED/api/analyzer/_search'
> 2021-02-04 16:58:45,334 [DEBUG] from play.shaded.ahc.org.asynchttpclient.netty.request.NettyRequestSender in AsyncHttpClient-9-2 - Using open Channel [id: 0x9016d965, L:/10.58.228.234:33394 - R:REMOVED/10.58.228.232:443]
>  for GET '/api/analyzer/_search'
> 2021-02-04 16:58:45,335 [DEBUG] from play.shaded.ahc.org.asynchttpclient.netty.channel.ChannelManager in AsyncHttpClient-9-2 - Adding key: http://REMOVED:80 for channel [id: 0xdebee49e, L:/10.58.228.234:56304 - R:REMOVED/10.58.228.232:80]
> 2021-02-04 16:58:45,341 [DEBUG] from play.shaded.ahc.org.asynchttpclient.netty.handler.HttpHandler in AsyncHttpClient-9-2 -
> 
> Request DefaultFullHttpRequest(decodeResult: success, version: HTTP/1.1, content: EmptyByteBufBE)
> GET /api/analyzer/_search HTTP/1.1
> Authorization: Bearer REMOVED
> host: REMOVED
> accept: */*
> user-agent: AHC/2.1
> 
> Response DefaultHttpResponse(decodeResult: success, version: HTTP/1.1)
> HTTP/1.1 404 Not Found
> Server: nginx/1.14.1
> Date: Thu, 04 Feb 2021 15:58:53 GMT
> Content-Type: application/json
> Content-Length: 61
> Connection: keep-alive
> 
> 2021-02-04 16:58:45,341 [DEBUG] from play.shaded.ahc.org.asynchttpclient.netty.channel.ChannelManager in AsyncHttpClient-9-2 - Adding key: https://REMOVED:443 for channel [id: 0x9016d965, L:/10.58.228.234:33394 - R:REMOVED/10.58.228.232:443]
> 2021-02-04 16:58:45,341 [INFO] from org.elastic4play.ErrorHandler in application-akka.actor.default-dispatcher-14741 - POST /api/connector/cortex/job returned 500
**> connectors.cortex.services.CortexError: Cortex error on http://REMOVED/api/analyzer/_search (404)
> {"type":"NotFoundError","message":"worker _search not found"}**
>         at connectors.cortex.services.CortexClient.$anonfun$request$3(CortexClient.scala:100)
>         at scala.util.Success.$anonfun$map$1(Try.scala:255)
>         at scala.util.Success.map(Try.scala:213)
>         at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
>         at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
>         at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
>         at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
>         at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:56)
>         at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:93)
>         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
>         at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
>         at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:93)
>         at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
>         at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
>         at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
>         at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
>         at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
>         at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
> 2021-02-04 16:58:46,021 [DEBUG] from play.shaded.ahc.org.asynchttpclient.netty.channel.DefaultChannelPool in AsyncHttpClient-timer-8-1 - Entry count for : http://REMOVED:80 : 1
> 2021-02-04 16:58:46,021 [DEBUG] from play.shaded.ahc.org.asynchttpclient.netty.channel.DefaultChannelPool in AsyncHttpClient-timer-8-1 - Entry count for : https://REMOVED:443 : 1
> 2021-02-04 16:58:46,080 [DEBUG] from play.shaded.ahc.org.asynchttpclient.netty.request.NettyRequestSender in application-akka.actor.default-dispatcher-14738 - Using pooled Channel '[id: 0xdebee49e, L:/10.58.228.234:56304 - R:REMOVED./10.58.228.232:80]' for 'GET' to 'http://REMOVED/api/status'
> 2021-02-04 16:58:46,080 [DEBUG] from play.shaded.ahc.org.asynchttpclient.netty.request.NettyRequestSender in application-akka.actor.default-dispatcher-14738 - Using open Channel [id: 0xdebee49e, L:/10.58.228.234:56304 - R:REMOVED./10.58.228.232:80] for GET '/api/status'

**Excerpt from /etc/thehive/application.conf**

> play.modules.enabled += connectors.cortex.CortexConnector
> 
> cortex {
>   "CERT-CORTEX" {
>     url = "http://REMOVED"
>     key = "REMOVED"
>     }
>   refreshDelay = 1 minute
>   maxRetryOnError = 3
>   statusCheckInterval = 1 minute
> }
> 

**Excerpt from /etc/cortex/application.conf**

> analyzer {
>   path = ["/opt/cortex/analyzers"]
> 
>   urls = [
>     "https://dl.bintray.com/thehive-project/cortexneurons/analyzers.json"
>   ]
> 
>   fork-join-executor {
>     parallelism-min = 2
>     parallelism-factor = 2.0
>     parallelism-max = 4
>   }
> }
> 
> responder {
>   urls = [
>     "https://dl.bintray.com/thehive-project/cortexneurons/responders.json"
>   ]
> 
>   fork-join-executor {
>     parallelism-min = 2
>     parallelism-factor = 2.0
>     parallelism-max = 4
>   }
> }
> 
> play.ws.proxy {
>     host = http://REMOVED
>     port = 8080
> }
> 
> play.http.secret.key="REMOVED"

**Comment by 0cta** [comment]
Bug was a fault in TheHive application.conf.
Falsely specified cortex URL as "http" instead of "https"...
