### ISSUE TITLE
MISP: Cortex module system…No modules found | TheHive: Select Cortex Server

### ISSUE THREAD

**Issue by khalidrehan** [TheHive-Project/Cortex#343]
### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 18.04
| Cortex version    | 3.1.0-1
| Package Type              |  From source

### Problem Description
Hello,
I enabled Plugin.Cortex_services, and I was using Cortex ver. 3.0.1-1 on port 9001, and it gave "OK"
Then I migrated to Cortex 3.1.0-1 successfully, but it is giving "No modules found".
![image](https://user-images.githubusercontent.com/37035465/107981528-4f0d8200-6fd3-11eb-9c75-f7850913e4f4.png)

Cortex is running fine, as well as MISP Modules service.
```
root@localhost:/home # curl 'http://localhost:9001/modules' -H 'Authorization: Bearer J1f2ICa0WZrK9+KQCPHj0gTBw2ZqI0Sw'
[]root@localhost:/home #
```
Where should I look for the problem?
Reference: https://github.com/MISP/misp-modules/issues/471

Regards,
Khalid.

**Comment by khalidrehan** [comment]
I believe the connection has been established but the there is no Cortex modules, which I don't actually understand.

**Comment by khalidrehan** [comment]
P.S: I migrated from older version using:
https://github.com/TheHive-Project/CortexDocs/blob/master/admin/upgrade_to_cortex_3_1_and_es7_x.md

**Comment by khalidrehan** [comment]
> ### Work Environment
> Question	Answer
> OS version (server)	Ubuntu 18.04
> Cortex version	3.1.0-1
> Package Type	From source
> ### Problem Description
> Hello,
> I enabled Plugin.Cortex_services, and I was using Cortex ver. 3.0.1-1 on port 9001, and it gave "OK"
> Then I migrated to Cortex 3.1.0-1 successfully, but it is giving "No modules found".
> ![image](https://user-images.githubusercontent.com/37035465/107981528-4f0d8200-6fd3-11eb-9c75-f7850913e4f4.png)
> 
> Cortex is running fine, as well as MISP Modules service.
> 
> ```
> root@localhost:/home # curl 'http://localhost:9001/modules' -H 'Authorization: Bearer J1f2ICa0WZrK9+KQCPHj0gTBw2ZqI0Sw'
> []root@localhost:/home #
> ```
> 
> Where should I look for the problem?
> Reference: [MISP/misp-modules#471](https://github.com/MISP/misp-modules/issues/471)
> 
> Regards,
> Khalid.

This part is fixed as I found the index cortex_4 not available.

**Comment by khalidrehan** [comment]
```
curl -u thehive:cyberx2020 http://localhost:9000/api/connector/cortex/analyzer?range=all

2021-03-10 01:50:26,400 [ERROR] from connectors.cortex.services.CortexAnalyzerSrv in application-akka.actor.default-dispatcher-38 - Request to Cortex fails
connectors.cortex.services.CortexError: Cortex error on http://localhost:9001/api/analyzer?range=all (403)
{"type":"AuthorizationError","message":"Insufficient rights to perform this action"}
        at connectors.cortex.services.CortexClient.$anonfun$request$3(CortexClient.scala:100)
        at scala.util.Success.$anonfun$map$1(Try.scala:255)
        at scala.util.Success.map(Try.scala:213)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:56)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:93)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:93)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
```

> Update:
> 
> ## TheHive: Select Cortex Server
> I have installed the "**Cortex Analyzers** and Responders", and TheHive is integrated but I can't run any analysis:
> ![image](https://user-images.githubusercontent.com/37035465/110556695-18e59d00-8150-11eb-9d54-1652f8e46690.png)
> 
> I believe this is the same problem.

**Comment by khalidrehan** [comment]
The cortex indices on Elasticsearch was cortex_5 instead of cortex_4 !!
And same for TheHive 16 instead of 15, and I don't know the reason for this.
