### ISSUE TITLE
Unable to update the user.

### ISSUE THREAD

**Issue by rleal124** [TheHive-Project/Cortex#348]
When I try edit a user I see the following error on log file, and on Web GUI I see the error: Unable to update the user.
My elastisearch version: 7.11.1
And Cortex version: 3.1.0-1

Some one can help me please? 
```
from org.elastic4play.database.DBConfiguration in application-akka.actor.default-dispatcher-28 - ElasticSearch request failure: POST:/cortex_5/_update/usernew%40mail.com?_source=true&refresh=wait_for&routing=usernew@mail.com&retry_on_conflict=5
StringEntity({"script":{"source":"ctx._source[\"name\"]=params.param0;ctx._source[\"roles\"]=params.param1;ctx._source[\"organization\"]=params.param2;ctx._source[\"updatedBy\"]=params.param3;ctx._source[\"updatedAt\"]=params.param4","params":{"param1":["read"],"param0":"user, new (ulocation)","param4":1614797651846,"param3":"admin","param2":"org"}}},Some(application/json))
 => ElasticError(mapper_parsing_exception,failed to parse,None,None,None,List(ElasticError(mapper_parsing_exception,failed to parse,None,None,None,null,None,None,None,List())),Some(CausedBy(illegal_argument_exception,unknown join name [user] for field [relations],Map())),None,None,List())
2021-03-03 18:54:11,852 [INFO] from org.thp.cortex.services.ErrorHandler in application-akka.actor.default-dispatcher-28 - PATCH /api/user/usernew@mail.com returned 500
org.elastic4play.InternalError: Unknown error: ElasticError(mapper_parsing_exception,failed to parse,None,None,None,List(ElasticError(mapper_parsing_exception,failed to parse,None,None,None,null,None,None,None,List())),Some(CausedBy(illegal_argument_exception,unknown join name [user] for field [relations],Map())),None,None,List())
        at org.elastic4play.database.DBConfiguration.$anonfun$execute$2(DBConfiguration.scala:158)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:56)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:93)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:93)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by rleal124** [comment]
I solve the problem by upgrade cortex to 3.1.1-1
