### ISSUE TITLE
Issues with cortex Analyzers 

### ISSUE THREAD

**Issue by hermanmaleiane** [TheHive-Project/Cortex#352]
Request Type
Issue

### Work Environment

| Question                        | Answer
|---------------------------|--------------------
| OS version (server)        |CentOS, RedHat, .
| Cortex version               | 3.1.1-1
| Package Type                | Docker

### Problem Description
I have installed cortex analyzers using this link  [](https://github.com/TheHive-Project/CortexDocs/blob/master/installation/install-guide.md#analyzers-and-responders) combined with [](https://hackmd.io/@D4rkw0lv3s/By0XCBJwD), but some analyzers doesn't work. 

I have pyhon 2.7 and 3.7 installed.

### Steps to Reproduce
1. Open Cortex Web
2. launch Abuse_Finder_3_0
3. Run analyzers
4. Go to Job report

Traceback (most recent call last):  File "/usr/lib/python3.7/sre_parse.py", line 1021, in parse_template    this = chr(ESCAPES[this][1])KeyError: '\\s'During handling of the above exception, another exception occurred:Traceback (most recent call last):  File "/opt/Cortex-Analyzers/analyzers/Abuse_Finder/abusefinder.py", line 9, in <module>    from abuse_finder import domain_abuse, ip_abuse, \  File "/usr/local/lib/python3.7/dist-packages/abuse_finder/__init__.py", line 2, in <module>    from .domain import domain_abuse  File "/usr/local/lib/python3.7/dist-packages/abuse_finder/domain.py", line 3, in <module>    from pythonwhois.net import get_whois_raw  File "/usr/local/lib/python3.7/dist-packages/pythonwhois/__init__.py", line 1, in <module>    from . import net, parse  File "/usr/local/lib/python3.7/dist-packages/pythonwhois/parse.py", line 363, in <module>    registrant_regexes = [preprocess_regex(regex) for regex in registrant_regexes]  File "/usr/local/lib/python3.7/dist-packages/pythonwhois/parse.py", line 363, in <listcomp>    registrant_regexes = [preprocess_regex(regex) for regex in registrant_regexes]  File "/usr/local/lib/python3.7/dist-packages/pythonwhois/parse.py", line 205, in preprocess_regex    regex = re.sub(r"\\s\*\(\?P<([^>]+)>\.\+\)", r"\s*(?P<\1>\S.*)", regex)  File "/usr/lib/python3.7/re.py", line 192, in sub    return _compile(pattern, flags).sub(repl, string, count)  File "/usr/lib/python3.7/re.py", line 309, in _subx    template = _compile_repl(template, pattern)  File "/usr/lib/python3.7/re.py", line 300, in _compile_repl    return sre_parse.parse_template(repl, pattern)  File "/usr/lib/python3.7/sre_parse.py", line 1024, in parse_template    raise s.error('bad escape %s' % this, len(this))re.error: bad escape \s at position 0

### Possible Solutions
I'm not sure if it's related to python environment because i tried to change from 2 to python3.

### Complementary information
![image](https://user-images.githubusercontent.com/13849459/111618480-1983d080-87ed-11eb-98ed-3255459962dc.png)

**Comment by hermanmaleiane** [comment]
I found the issue with docker neurons as well.
The strange thing is that it's happening with all my analyzers this time.
Abuse Finder
![image](https://user-images.githubusercontent.com/13849459/113888508-b4574580-97c2-11eb-90ac-01bc91e8163c.png)

Logs 
fo] o.t.c.s.DockerJobRunnerSrv - Execute container f7060ed3c48f5d0beaee0abc50e4230e94513aaf60706b7ccc63673c77a7f157
  timeout: 30 minutes
  image  : cortexneurons/abuse_finder:3
  volume : /tmp/cortex-jobs/cortex-job-2ITFrHgB_iAW1QPtOjpT-26387196434742254:/job
[info] c.s.d.c.DefaultDockerClient - Starting container with Id: f7060ed3c48f5d0beaee0abc50e4230e94513aaf60706b7ccc63673c77a7f157
[info] o.t.c.s.AuditActor - Job 2ITFrHgB_iAW1QPtOjpT has be updated (JsDefined("Failure"))
[info] o.t.c.s.JobSrv - Job 2ITFrHgB_iAW1QPtOjpT has finished with status Failure
[info] o.t.c.s.JobSrv - Looking for similar job in the last 10 minutes (worker=6ce0cc30053f040b1125bd0ec80a5f98, dataType=ip, data=Left(8.8.8.8), tlp=2, parameters={})
[warn] o.t.c.s.JobRunnerSrv - worker 6ce0cc30053f040b1125bd0ec80a5f98 can't be run with docker (doesn't have image)
[info] o.t.c.s.ProcessJobRunnerSrv - Execute /opt/Cortex-Analyzers/analyzers/GoogleDNS/GoogleDNS_resolve.py in /opt/Cortex-Analyzers/analyzers, timeout is 30 minutes
[info] o.t.c.s.AuditActor - Job yYTRrHgB_iAW1QPt-zyl has be updated (JsDefined("InProgress"))
[info] o.t.c.s.JobSrv - Job yYTRrHgB_iAW1QPt-zyl has finished with status Failure
[info] o.t.c.s.AuditActor - Job yYTRrHgB_iAW1QPt-zyl has be updated (JsDefined("Failure"))


cortexneurons/googledns_resolve

![image](https://user-images.githubusercontent.com/13849459/113888964-16b04600-97c3-11eb-91e6-d0a668540f56.png)

[info] o.t.c.s.DockerJobRunnerSrv - Execute container 2ec396de109bec4f2cb704906271fa69617feddab9c7f042bb9ae5a071f50323
  timeout: 30 minutes
  image  : cortexneurons/googledns_resolve:1
  volume : /tmp/cortex-jobs/cortex-job-Q4TTrHgB_iAW1QPtGj3u-8755731655813227546:/job
[info] c.s.d.c.DefaultDockerClient - Starting container with Id: 2ec396de109bec4f2cb704906271fa69617feddab9c7f042bb9ae5a071f50323
[info] o.t.c.s.JobSrv - Job Q4TTrHgB_iAW1QPtGj3u has finished with status Failure
[info] o.t.c.s.AuditActor - Job Q4TTrHgB_iAW1QPtGj3u has be updated (JsDefined("Failure"))


This link resource was my guide:
https://github.com/TheHive-Project/CortexDocs/blob/master/installation/install-guide.md#docker

Thanks in advance!!
