### ISSUE TITLE
Oauth2 Authentication error Azure AD SSO

### ISSUE THREAD

**Issue by mekhaleraj** [TheHive-Project/Cortex#435]
Bug 

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | Ubuntu 22.04, Azure VM
| Cortex version / git hash   | 3.1.7-1
| Package Type              | Binary

Followed below guide for the instalation.
https://docs.thehive-project.org/cortex/installation-and-configuration/step-by-step-guide/

### Problem Description
Configured Oauth2 authentication with Cortex and Azure AD.
After successful login at MS, Connection timeout error observed at redirection time. 

### Steps to Reproduce
Enable Oauth2 and configure Azure AD
Login with MS account

### Complementary information
2022-11-09 14:22:50,056 [ERROR] from org.elastic4play.services.auth.MultiAuthSrv in application-akka.actor.default-dispatcher-39 - Authentication failure
org.elastic4play.AuthenticationError: OAuth2 authentication failure: OAuth2 token verification failure Request timeout to login.microsoftonline.com:443 after 120000 ms
	at org.thp.cortex.services.OAuth2Srv$$anonfun$$nestedInanonfun$authenticate$1$1.applyOrElse(OAuth2Srv.scala:96)
	at org.thp.cortex.services.OAuth2Srv$$anonfun$$nestedInanonfun$authenticate$1$1.applyOrElse(OAuth2Srv.scala:95)
	at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:417)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
2022-11-09 14:22:50,057 [INFO] from org.thp.cortex.services.AccessLogFilter in application-akka.actor.default-dispatcher-39 - 127.0.0.1 GET /api/ssoLogin?code=<DELETED> took 120071ms and returned 401 65 byte

**Comment by mekhaleraj** [comment]
Issue resolved. Missing proxy usage. Fixed by TheHive team
