### ISSUE TITLE
Cortex INFO] from play.api.Play in main - Application started (Prod) (no global state)

### ISSUE THREAD

**Issue by uliseschombo** [TheHive-Project/Cortex#445]
Install the cortex and elastic search on a ubuntu server:}

Elastic search was running ok
cortex suppose the same:

● cortex.service - cortex
     Loaded: loaded (/etc/systemd/system/cortex.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2023-06-07 05:18:32 UTC; 7s ago
       Docs: https://thehive-project.org
   Main PID: 2237347 (java)
      Tasks: 41 (limit: 19066)
     Memory: 475.8M
     CGroup: /system.slice/cortex.service
             └─2237347 java -Duser.dir=/opt/cortex -Dconfig.file=/etc/cortex/application.conf -Dlogger.file=/etc/cortex/logback.xml -D>

Jun 07 05:18:32 ins-pdt-app01 systemd[1]: Started cortex.

but when i run a tail i see that:
tail -f /var/log/cortex/application.log
2023-06-07 05:18:50,042 [INFO] from module in main - Loading model class org.thp.cortex.models.WorkerModel
2023-06-07 05:18:50,042 [INFO] from module in main - Loading model class org.thp.cortex.models.UserModel
2023-06-07 05:18:50,042 [INFO] from module in main - Loading model class org.thp.cortex.models.OrganizationModel
2023-06-07 05:18:50,043 [INFO] from module in main - Loading model class org.thp.cortex.models.ReportModel
2023-06-07 05:18:50,051 [INFO] from module in main - Loading authentication module class org.thp.cortex.services.KeyAuthSrv
2023-06-07 05:18:50,051 [INFO] from module in main - Loading authentication module class org.elastic4play.services.auth.LdapAuthSrv
2023-06-07 05:18:50,051 [INFO] from module in main - Loading authentication module class org.thp.cortex.services.OAuth2Srv
2023-06-07 05:18:50,051 [INFO] from module in main - Loading authentication module class org.elastic4play.services.auth.ADAuthSrv
2023-06-07 05:18:50,051 [INFO] from module in main - Loading authentication module class org.thp.cortex.services.LocalAuthSrv
2023-06-07 05:18:50,910 [INFO] from akka.event.slf4j.Slf4jLogger in application-akka.actor.default-dispatcher-4 - Slf4jLogger started
2023-06-07 05:18:53,085 [INFO] from org.apache.http.impl.execchain.RetryExec in jersey-client-async-executor-0 - I/O exception (java.io.IOException) caught when processing request to {}->unix://localhost:80: Permission denied
2023-06-07 05:18:53,086 [INFO] from org.apache.http.impl.execchain.RetryExec in jersey-client-async-executor-0 - Retrying request to {}->unix://localhost:80
2023-06-07 05:18:53,087 [INFO] from org.apache.http.impl.execchain.RetryExec in jersey-client-async-executor-0 - I/O exception (java.io.IOException) caught when processing request to {}->unix://localhost:80: Permission denied
2023-06-07 05:18:53,087 [INFO] from org.apache.http.impl.execchain.RetryExec in jersey-client-async-executor-0 - Retrying request to {}->unix://localhost:80
2023-06-07 05:18:53,087 [INFO] from org.apache.http.impl.execchain.RetryExec in jersey-client-async-executor-0 - I/O exception (java.io.IOException) caught when processing request to {}->unix://localhost:80: Permission denied
2023-06-07 05:18:53,087 [INFO] from org.apache.http.impl.execchain.RetryExec in jersey-client-async-executor-0 - Retrying request to {}->unix://localhost:80
2023-06-07 05:18:53,092 [INFO] from org.thp.cortex.services.DockerJobRunnerSrv in main - Docker is not available
com.spotify.docker.client.exceptions.DockerException: java.util.concurrent.ExecutionException: javax.ws.rs.ProcessingException: java.io.IOException: Permission denied
	at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:2828)
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:2692)
	at com.spotify.docker.client.DefaultDockerClient.info(DefaultDockerClient.java:595)
	at org.thp.cortex.services.DockerJobRunnerSrv.$anonfun$isAvailable$3(DockerJobRunnerSrv.scala:53)
	at play.api.LoggerLike.info(Logger.scala:136)
	at play.api.LoggerLike.info$(Logger.scala:133)
	at play.api.Logger.info(Logger.scala:233)
	at org.thp.cortex.services.DockerJobRunnerSrv.$anonfun$isAvailable$1(DockerJobRunnerSrv.scala:53)
	at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:23)
	at scala.util.Try$.apply(Try.scala:213)
	at org.thp.cortex.services.DockerJobRunnerSrv.isAvailable$lzycompute(DockerJobRunnerSrv.scala:51)
	at org.thp.cortex.services.DockerJobRunnerSrv.isAvailable(DockerJobRunnerSrv.scala:50)
	at org.thp.cortex.services.JobRunnerSrv$$anonfun$1.applyOrElse(JobRunnerSrv.scala:50)
	at org.thp.cortex.services.JobRunnerSrv$$anonfun$1.applyOrElse(JobRunnerSrv.scala:49)
	at scala.PartialFunction.$anonfun$runWith$1$adapted(PartialFunction.scala:145)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at scala.collection.TraversableLike.collect(TraversableLike.scala:407)
	at scala.collection.TraversableLike.collect$(TraversableLike.scala:405)
	at scala.collection.AbstractTraversable.collect(Traversable.scala:108)
	at org.thp.cortex.services.JobRunnerSrv.<init>(JobRunnerSrv.scala:49)
	at org.thp.cortex.services.JobRunnerSrv$$FastClassByGuice$$40676336.GUICE$TRAMPOLINE(<generated>)
	at org.thp.cortex.services.JobRunnerSrv$$FastClassByGuice$$40676336.apply(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:40)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:60)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:40)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:60)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:213)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:186)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:113)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at com.google.inject.Guice.createInjector(Guice.java:78)
	at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:200)
	at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:155)
	at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
	at play.core.server.ProdServerStart$.start(ProdServerStart.scala:53)
	at play.core.server.ProdServerStart$.main(ProdServerStart.scala:29)
	at play.core.server.ProdServerStart.main(ProdServerStart.scala)
Caused by: java.util.concurrent.ExecutionException: javax.ws.rs.ProcessingException: java.io.IOException: Permission denied
	at jersey.repackaged.com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299)
	at jersey.repackaged.com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286)
	at jersey.repackaged.com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:2690)
	... 53 common frames omitted
Caused by: javax.ws.rs.ProcessingException: java.io.IOException: Permission denied
	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:481)
	at org.glassfish.jersey.apache.connector.ApacheConnector$1.run(ApacheConnector.java:491)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at jersey.repackaged.com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:299)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118)
	at jersey.repackaged.com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:50)
	at jersey.repackaged.com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:37)
	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:487)
	at org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:178)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340)
	at org.glassfish.jersey.client.ClientRuntime$3.run(ClientRuntime.java:210)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: Permission denied
	at jnr.unixsocket.UnixSocketChannel.doConnect(UnixSocketChannel.java:127)
	at jnr.unixsocket.UnixSocketChannel.connect(UnixSocketChannel.java:136)
	at jnr.unixsocket.UnixSocketChannel.connect(UnixSocketChannel.java:223)
	at com.spotify.docker.client.UnixConnectionSocketFactory.connectSocket(UnixConnectionSocketFactory.java:85)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:435)
	... 21 common frames omitted
2023-06-07 05:18:53,533 [WARN] from org.thp.cortex.services.JobRunnerSrv in main - The package cortexutils for python hasn't been found
2023-06-07 05:18:53,539 [WARN] from org.thp.cortex.services.JobRunnerSrv in main - The package cortexutils for python2 hasn't been found
2023-06-07 05:18:53,566 [INFO] from org.thp.cortex.services.WorkerSrv in application-akka.actor.default-dispatcher-4 - New worker list:

	RiskIQ_Certificates 1.0
	IPVoid 1.0
	SEKOIAIntelligenceCenter_Indicators 1.0
	RiskIQ_Projects 1.0
	Shuffle 1.0
	SEKOIAIntelligenceCenter_Context 1.0
	RiskIQ_Cookies 1.0
	HIBP_Query 2.0
	CheckPoint_Unlock 1.0
	DNSSinkhole 1.0
	DomainToolsIris_Investigate 1.0
	ThreatMiner 1.0
	MSDefender-UnisolateMachine 1.0
	Autofocus_SearchJSON 1.0
	MSDefender-PushIOC-Block 1.0
	DomainTools_Reputation 2.0
	PaloAltoCortexXDR_isolate 1.0
	AMPforEndpoints_SCDAdd 1.0
	MaxMind_GeoIP 4.0
	Crowdstrike_Falcon_Custom_IOC_API 1.0
	FileInfo 8.0
	PaloAltoNGFW_block_external_user 1.0.0
	SentinelOne_Hash_Blacklister 1.0
	CheckPoint_Lock 1.0
	FireEyeiSight 1.0
	Malwares_GetReport 1.0
	Mnemonic_pDNS_Public 3.0
	SEKOIAIntelligenceCenter_Observables 1.0
	THOR_Thunderstorm_ScanSample 0.3.1
	Verifalia 1.0
	RiskIQ_Articles 1.0
	DomainTools_Risk 2.0
	EchoTrail 1.0
	PassiveTotal_Osint 2.0
	IP-API 1.0
	CIRCLPassiveDNS 2.0
	CyberChef_FromHex 1.0
	PaloAltoNGFW_block_port_for_external_communication 2.0.0
	PassiveTotal_Passive_Dns 2.1
	Shodan_Host 1.0
	SendGrid 1.0
	DomainTools_WhoisLookupUnparsed 2.0
	Hashdd_Detail 2.0
	RiskIQ_Resolutions 1.0
	PassiveTotal_Host_Pairs 2.0
	Hunterio_DomainSearch 1.0
	CyberChef_FromCharCode 1.0
	MISPWarningLists 2.0
	Gmail_BlockDomain 1.0
	DomainTools_ReverseIPWhois 2.0
	AbuseIPDB 1.0
	TorProject 1.0
	Redmine_Issue 1.0
	CIRCLPassiveSSL 2.0
	Inoitsu 1.0
	Fortiguard_URLCategory 2.1
	Splunk_Search_User_Agent 3.0
	RiskIQ_HostpairParents 1.0
	Yara 2.0
	VirusTotal_Scan 3.1
	EmergingThreats_DomainInfo 1.0
	DNSDB_DomainName 2.0
	PhishTank_CheckURL 2.1
	DNS-RPZ 1.0
	MailIncidentStatus 1.0
	PaloAltoNGFW_block_internal_domain 2.0.0
	StamusNetworks_HostID 1.0
	IPinfo_Hosted_Domains 1.0
	RiskIQ_Subdomains 1.0
	EmlParser 2.1
	SpamhausDBL 1.0
	SophosIntelix_GetReport 0.3
	PassiveTotal_Trackers 2.0
	ThreatResponse 1.0
	VirusTotal_GetReport 3.1
	Gmail_BlockSender 1.0
	Maltiverse_Report 1.0
	SophosIntelix_Submit_Dynamic 0.1
	MSDefenderOffice365_unblock 1.0
	BackscatterIO_GetObservations 1.0
	OTXQuery 2.0
	Investigate_Sample 1.0
	PaloAltoNGFW_unblock_port_for_internal_communication 1.0.0
	MetaDefenderCloud_Reputation 1.0
	Autofocus_SearchIOC 1.0
	Splunk_Search_Mail_Email 3.0
	CheckPhish 1.0
	LastInfoSec 1.0
	Patrowl_GetReport 1.0
	NSRL 1.0
	AMPforEndpoints_MoveGUID 1.0
	RT4-CreateTicket 1.0
	PhishingInitiative_Scan 1.0
	Mailer 1.0
	RiskIQ_Summary 1.0
	C1fApp 1.0
	Diario_Scan 1.0
	MSDefenderOffice365_block 1.0
	Zscaler 1.3
	RecordedFuture_risk 1.0
	OpenCTI_SearchObservables 2.0
	Nessus 2.0
	KnowBe4 1.0
	SecurityTrails_Passive_DNS 1.0
	Cylance 1.0
	SentinelOne_DeepVisibility_DNSQuery 1.0
	Virusshare 2.0
	Velociraptor_Flow 0.1
	DomainTools_ReverseIP 2.0
	Crowdsec_Analyzer 1.0
	Yeti 1.0
	StaxxSearch 1.0
	PaloAltoNGFW_unblock_external_domain 1.0.0
	SinkDB 1.1
	PaloAltoNGFW_unblock_external_IP_address 1.0.0
	MalwareBazaar 1.0
	DomainToolsIris_AddRiskyDNSTag 1.0
	Robtex_Forward_PDNS_Query 1.0
	CheckPhish_Submit 1.0
	RiskIQ_Services 1.0
	WOT_Lookup 2.0
	JoeSandbox_File_Analysis_Inet 3.0
	RiskIQ_Whois 1.0
	JoeSandbox_File_Analysis_Noinet 3.0
	Elasticsearch_Analysis 1.0
	Splunk_Search_Hash 3.0
	Autofocus_GetSampleAnalysis 1.0
	Virustotal_Downloader 0.1
	DuoUnlockUserAccount 1.0
	PaloAltoNGFW_unblock_internal_user 1.0.0
	EmergingThreats_IPInfo 1.0
	Shodan_ReverseDNS 1.0
	Shodan_Host_History 1.0
	Wazuh 1.0
	PassiveTotal_Whois_Details 2.0
	BitcoinAbuse 1.0
	Urlscan.io_Search 0.1.1
	CIRCLHashlookup 1.1
	PaloAltoNGFW_block_external_IP_address 2.0.0
	DomainTools_WhoisLookup 2.0
	PaloAltoNGFW_block_internal_IP_address 2.0.0
	GRR 0.1
	Cyberprotect_ThreatScore 3.0
	PaloAltoNGFW_block_external_domain 2.0.0
	ZEROFOX_Close_alert 1.0
	Minemeld 1.0
	PassiveTotal_Malware 2.0
	DomainTools_ReverseNameServer 2.0
	IntezerCommunity 1.0
	DNSDB_IPHistory 2.0
	Ldap_Query 2.0
	PaloAltoNGFW_unblock_internal_domain 1.0.0
	GoogleSafebrowsing 2.0
	PassiveTotal_Enrichment 2.0
	PayloadSecurity_File_Analysis 1.0
	Triage 1.0
	Msg_Parser 3.0
	PaloAltoWildFire 1.0
	DomainMailSPFDMARC_Analyzer 1.1
	PassiveTotal_Unique_Resolutions 2.0
	Splunk_Search_User 3.0
	RiskIQ_PushArtifactToProject 1.0
	CuckooSandbox_Url_Analysis 1.2
	BackscatterIO_Enrichment 1.0
	DomainTools_ReverseWhois 2.0
	SophosIntelix_Submit_Static 0.1
	Threatcrowd 1.0
	Umbrella_Blacklister 1.1
	ZEROFOX_Takedown_request 1.0
	CyberCrime-Tracker 1.0
	Gmail_DeleteMessage 1.0
	EmailRep 1.0
	KasperskyThreatIntelligencePortal 1.0
	URLhaus 2.0
	MISP 2.1
	TeamCymruMHR 1.0
	DShield_lookup 1.0
	EmergingThreats_MalwareInfo 1.0
	StopForumSpam 1.0
	DomainTools_HostingHistory 2.0
	CyberChef_FromBase64 1.0
	VirusTotal_Rescan 3.1
	Abuse_Finder 3.0
	Investigate_Categorization 1.0
	SecurityTrails_Whois 1.0
	DomainTools_WhoisHistory 2.0
	VirusTotal_DownloadSample 3.1
	MetaDefenderCloud_Scan 1.0
	PassiveTotal_Ssl_Certificate_History 2.0
	Splunk_Search_Other 3.0
	Malpedia 1.0
	MetaDefenderCore_Scan 1.0
	Splunk_Search_Registry 3.0
	RiskIQ_Malware 1.0
	Crt_sh_Transparency_Logs 1.0
	PaloAltoCortexXDR_scan 1.0
	IPinfo_Details 1.0
	CERTatPassiveDNS 2.0
	Urlscan.io_Scan 0.1.0
	RiskIQ_Components 1.0
	DomainToolsIris_CheckMaliciousTags 1.0
	ProofPoint_Lookup 1.0
	PayloadSecurity_Url_Analysis 1.0
	MSDefender-FullVirusscan 1.0
	Shodan_DNSResolve 1.0
	Splunk_Search_Mail_Subject 3.0
	VMRay 4.1
	GoogleDNS_resolve 1.0.0
	DomainToolsIris_Pivot 1.0
	MetaDefenderCloud_GetReport 1.0
	FalconSandbox 1.0
	OpenCTI_SearchExactObservable 2.0
	Hipposcore 2.0
	Shodan_InfoDomain 1.0
	CuckooSandbox_File_Analysis_Inet 1.2
	DNS_Lookingglass 1.0
	GoogleVisionAPI_WebDetection 1.0.0
	Valhalla_GetRuleMatches 0.3.1
	TalosReputation 1.0
	RiskIQ_Trackers 1.0
	Vulners_CVE 1.0
	Splunk_Search_IP 3.0
	TorBlutmagie 1.0
	SpamAssassin 1.0
	Splunk_Search_Domain_FQDN 3.0
	MSDefender-IsolateMachine 1.0
	RiskIQ_Reputation 1.0
	FireHOLBlocklists 2.0
	Vulners_IOC 1.0
	NERD 1.0
	RiskIQ_Artifacts 1.0
	ThreatGrid 1.0
	Robtex_Reverse_PDNS_Query 1.0
	Gmail_UnblockDomain 1.0
	PassiveTotal_Ssl_Certificate_Details 2.0
	PaloAltoNGFW_block_internal_user 1.0.0
	AMPforEndpoints_IsolationStart 1.0
	Hashdd_Status 2.0
	PaloAltoNGFW_unblock_port_for_external_communication 1.0.0
	PaloAltoCortexXDR_unisolate 1.0
	PaloAltoNGFW_unblock_internal_IP_address 1.0.0
	DNSDB_NameHistory 2.0
	PhishingInitiative_Lookup 2.0
	AMPforEndpoints_IsolationStop 1.0
	SoltraEdge 1.0
	Pulsedive_GetIndicator 1.0
	QRadar_Auto_Closing_Offense 1.0
	IBMXForce_Lookup 1.0
	Gmail_UnblockSender 1.0
	Splunk_Search_URL_URI_Path 3.0
	RiskIQ_HostpairChildren 1.0
	IVRE 1.0
	MSDefender-PushIOC-Alert 1.0
	JoeSandbox_Url_Analysis 2.0
	GreyNoise 3.1
	Censys 1.0
	CISMCAP 1.0
	Malwares_Scan 1.0
	Robtex_IP_Query 1.0
	HippoMore 2.0
	PaloAltoNGFW_unblock_external_user 1.0.0
	HybridAnalysis_GetReport 1.0
	DuoLockUserAccount 1.0
	AMPforEndpoints_SCDRemove 1.0
	ClamAV_FileInfo 1.1
	PaloAltoNGFW_block_port_for_internal_communication 2.0.0
	ForcepointWebsensePing 1.0
	Shodan_Search 2.0
	Umbrella_Report 1.0
	PassiveTotal_Components 2.0
	AzureTokenRevoker 1.0
	MetaDefenderCore_GetReport 1.0
	Diario_GetReport 1.0
	MalwareClustering_Search 1.0
	Mnemonic_pDNS_Closed 3.0
	Splunk_Search_File_Filename 3.0
	UnshortenLink 1.2
	Onyphe_Summary 1.0
	AnyRun_Sandbox_Analysis 1.0

2023-06-07 05:18:53,936 [WARN] from org.thp.cortex.services.JobRunnerSrv in main - The package cortexutils for python3 hasn't been found
2023-06-07 05:18:54,042 [INFO] from com.sksamuel.elastic4s.http.JavaClient$ in main - Creating HTTP client on http://ins-pdt-app01:901
2023-06-07 05:18:54,252 [WARN] from org.elastic4play.database.SearchWithScroll in application-akka.actor.default-dispatcher-5 - Search error
com.sksamuel.elastic4s.http.JavaClientExceptionWrapper: java.net.ConnectException: Connection refused
	at com.sksamuel.elastic4s.http.JavaClient$$anon$1.onFailure(JavaClient.scala:70)
	at org.elasticsearch.client.RestClient$FailureTrackingResponseListener.onDefinitiveFailure(RestClient.java:668)
	at org.elasticsearch.client.RestClient$1.failed(RestClient.java:417)
	at org.apache.http.concurrent.BasicFuture.failed(BasicFuture.java:137)
	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.executionFailed(DefaultClientExchangeHandlerImpl.java:101)
	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.failed(AbstractClientExchangeHandler.java:426)
	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.connectionRequestFailed(AbstractClientExchangeHandler.java:348)
	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.access$100(AbstractClientExchangeHandler.java:62)
	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler$1.failed(AbstractClientExchangeHandler.java:392)
	at org.apache.http.concurrent.BasicFuture.failed(BasicFuture.java:137)
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager$1.failed(PoolingNHttpClientConnectionManager.java:316)
	at org.apache.http.concurrent.BasicFuture.failed(BasicFuture.java:137)
	at org.apache.http.nio.pool.RouteSpecificPool.failed(RouteSpecificPool.java:162)
	at org.apache.http.nio.pool.AbstractNIOConnPool.requestFailed(AbstractNIOConnPool.java:609)
	at org.apache.http.nio.pool.AbstractNIOConnPool$InternalSessionRequestCallback.failed(AbstractNIOConnPool.java:889)
	at org.apache.http.impl.nio.reactor.SessionRequestImpl.failed(SessionRequestImpl.java:162)
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvent(DefaultConnectingIOReactor.java:176)
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:148)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:351)
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:221)
	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777)
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvent(DefaultConnectingIOReactor.java:174)
	... 5 common frames omitted
2023-06-07 05:18:54,270 [INFO] from play.api.Play in main - Application started (Prod) (no global state)
2023-06-07 05:18:54,270 [INFO] from play.api.Play in main - Application started (Prod) (no global state)

as well when i try to open cortex on a web browser is not possible to do that

**Comment by misterKr4bs** [comment]
Get this same thing.. Any update on this issue? or has a solution been found?
