### ISSUE TITLE
Cortex 2 is not passing proxy variable to analyzers

### ISSUE THREAD

**Issue by robertnixon2003** [TheHive-Project/Cortex#71]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| Cortex version / git hash   | 2
| Package Type              | DEB

### Problem Description
Proxy settings are set in the GUI, analyzer runs for a while and then times out since it is not going through the proxy. Hitting the firewall and being dropped. 

### Complementary information

```
Invalid output
Traceback (most recent call last):
  File "Fortiguard/urlcategory.py", line 53, in <module>
    URLCategoryAnalyzer().run()
  File "Fortiguard/urlcategory.py", line 41, in run
    req = requests.get(url)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.fortiguard.com', port=443): Max retries exceeded with url: /webfilter?q=test.com (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f083b9553d0>: Failed to establish a new connection: [Errno 101] Network is unreachable',))
```

**Comment by nadouani** [comment]
Well, the issue is an incompatibility between Cortex 2 and cortexutils. The proxy config names have been changed by Cortex 2 but the change has not been made on cortexutils.

We will release a new version of cortexutils library

**Comment by robertnixon2003** [comment]
When will this be in the DEB package?

**Comment by nadouani** [comment]
Once Bintray comes up again :)
