### ISSUE TITLE
Coretxutils and TypeError: argument of type 'bool' is not iterable

### ISSUE THREAD

**Issue by robertnixon2003** [TheHive-Project/Cortex#73]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| OS version (client)       | 16
| Cortex version / git hash   | 2
| Package Type              | DEB

### Steps to Reproduce
Run MISP or MISPWarninglist analyzer with a hash or domain type observable

```
Invalid output
Traceback (most recent call last):
  File "MISPWarningLists/mispwarninglists.py", line 96, in <module>
    MISPWarninglistsAnalyzer().run()
  File "MISPWarningLists/mispwarninglists.py", line 77, in run
    "is_uptodate": self.lastlocalcommit() == self.lastremotecommit()
  File "/usr/local/lib/python2.7/dist-packages/cortexutils/analyzer.py", line 202, in report
    'artifacts': self.artifacts(full_report),
  File "/usr/local/lib/python2.7/dist-packages/cortexutils/analyzer.py", line 157, in artifacts
    return extractor.check_iterable(raw)
  File "/usr/local/lib/python2.7/dist-packages/cortexutils/extractor.py", line 183, in check_iterable
    dt = self.__checktype(item)
  File "/usr/local/lib/python2.7/dist-packages/cortexutils/extractor.py", line 128, in __checktype
    if self.ignore and self.ignore in value:
TypeError: argument of type 'bool' is not iterable
```

```
Invalid output
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:794: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
Traceback (most recent call last):
  File "MISP/misp.py", line 73, in <module>
    MISPAnalyzer().run()
  File "MISP/misp.py", line 69, in run
    self.report({'results': response})
  File "/usr/local/lib/python3.5/dist-packages/cortexutils/analyzer.py", line 202, in report
    'artifacts': self.artifacts(full_report),
  File "/usr/local/lib/python3.5/dist-packages/cortexutils/analyzer.py", line 157, in artifacts
    return extractor.check_iterable(raw)
  File "/usr/local/lib/python3.5/dist-packages/cortexutils/extractor.py", line 181, in check_iterable
    results.extend(self.check_iterable(item))
  File "/usr/local/lib/python3.5/dist-packages/cortexutils/extractor.py", line 170, in check_iterable
    results.extend(self.check_iterable(item))
  File "/usr/local/lib/python3.5/dist-packages/cortexutils/extractor.py", line 181, in check_iterable
    results.extend(self.check_iterable(item))
  File "/usr/local/lib/python3.5/dist-packages/cortexutils/extractor.py", line 170, in check_iterable
    results.extend(self.check_iterable(item))
  File "/usr/local/lib/python3.5/dist-packages/cortexutils/extractor.py", line 181, in check_iterable
    results.extend(self.check_iterable(item))
  File "/usr/local/lib/python3.5/dist-packages/cortexutils/extractor.py", line 170, in check_iterable
    results.extend(self.check_iterable(item))
  File "/usr/local/lib/python3.5/dist-packages/cortexutils/extractor.py", line 183, in check_iterable
    dt = self.__checktype(item)
  File "/usr/local/lib/python3.5/dist-packages/cortexutils/extractor.py", line 128, in __checktype
    if self.ignore and self.ignore in value:
TypeError: argument of type 'bool' is not iterable
```

**Comment by 3c7** [comment]
Thanks for reporting. The fix is already shipped, but the package needs to get released on pypi. You can already use the package that comes with Cortex-Analyzers (installing via the setup.py under `contrib` directory).

**Comment by 3c7** [comment]
I'll close this, after the package has been published.

**Comment by 3c7** [comment]
Published: https://pypi.python.org/pypi/cortexutils/1.2.2
