### ISSUE TITLE
Insufficient Rights To Perform This Action

### ISSUE THREAD

**Issue by hackdefendr** [TheHive-Project/Cortex#87]
# Insufficient Rights To Perform This Action

### Request Type
Bug or Issue

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| OS version (client)       | Ubuntu
| Cortex version / git hash   | Current
| Package Type              | Binary
| Browser type & version    | Chrome

### Problem Description
When I click on the Cortex logo to go back to the main analyzers page, I receive a little red pop up that reads Insufficient Rights To Perform Action

### Steps to Reproduce
1. Follow the instructions for installation
1. Follow the steps for configuration
1. Try to access the main Cortex analyzers page
1. I really don't know

### Possible Solutions
I tried giving ownership of my Cortex-Analyzer folder to the user cortex, but this had no effect. I am stuck and do not know what else to look for.

### Complementary information
```
2018-04-10 13:21:32,454 [INFO] from org.thp.cortex.services.ErrorHandler in application-akka.actor.default-dispatcher-172 - GET /api/analyzer?rang
e=all returned 403
org.elastic4play.AuthorizationError: Insufficient rights to perform this action
        at org.elastic4play.controllers.Authenticated$$anon$1.$anonfun$invokeBlock$1(Authenticated.scala:240)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:304)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by 3c7** [comment]
The errormessage refers to the web ui directly and should have nothing to do with the analyzers directory. If you reload the whole page, are you still logged in? Are you logged in as a superadmin or as an orgadmin?

**Comment by 3c7** [comment]
Okay, have you created another Organisation? The members of the cortex org are (as superadmins) not able to use analyzers.

**Comment by hackdefendr** [comment]
Well no I had not, because that step was not documented anyplace that I could find. 

This did resolve my issue though.  Thanks.

**Comment by nadouani** [comment]
Hello @hackdefendr, I’m sorry but if you have followed the steps of the Quick start guide, you could have find your issue.

https://github.com/TheHive-Project/CortexDocs/blob/master/admin/quick-start.md

That said, clicking on the logo should redirect to the right page, which is not correcly working here.

**Comment by hackdefendr** [comment]
I followed the Ubuntu (deb package) install, that links to the
configuration document. I did not use the quick start guide. Maybe the
quick start guide should be part of ALL documentation.

The steps I used do not mention creating a new organization and user.

**Comment by 3c7** [comment]
We're aware that our documentation needs some polish. At the bottom of the deb installation guide the configuration guide is linked which mentions the different types of user accounts, also. But doesn't matter, good it works for you now.

**Comment by kmahyyg** [comment]
Same issue here... Using "run with docker" guide, not mention this problem...
